"use client";

import { useCallback, useEffect, useMemo, useState } from "react";
import Link from "next/link";
import type { AdminAnalytics, QuestionCategory, ScoreSummary } from "@/lib/contracts";
import { ApiError, errorMessage, getData } from "@/lib/api";
import { adminAnalyticsPath, categoryLabel, contractSearch, countLabel, scoreLabel, validMonth } from "@/lib/feedback-contract";
import { useListSearchParams } from "./pagination";
import { EmptyState, ErrorAlert, LoadingCards } from "./ui";

const categories:QuestionCategory[]=["OVERALL_EXPERIENCE","DRIVING_SAFETY","PUNCTUALITY","CLEANLINESS","PROFESSIONALISM","VEHICLE_CONDITION","CUSTOM"];
export function AdminAnalyticsView(){
  const search=useListSearchParams(); const [data,setData]=useState<AdminAnalytics|null>(null);const [loading,setLoading]=useState(false);const [error,setError]=useState<ApiError|null>(null);
  const filters=useMemo(()=>{const p=search.parameters;return {month:validMonth(p.get("month"))?p.get("month")!:undefined,driverId:p.get("driverId")||undefined,driverSource:(p.get("driverSource")||undefined) as "AGENCY"|"OUTSOURCED"|undefined,vendorId:p.get("vendorId")||undefined,category:(p.get("category")||undefined) as QuestionCategory|undefined}},[search.parameters]);
  const path=search.ready?adminAnalyticsPath(filters):null;
  const load=useCallback(async()=>{if(!path)return;setLoading(true);setError(null);try{setData(await getData<AdminAnalytics>(path))}catch(cause){setError(cause instanceof ApiError?cause:new ApiError(0,"NETWORK_UNAVAILABLE",errorMessage(cause)))}finally{setLoading(false)}},[path]);
  useEffect(()=>{queueMicrotask(()=>void load())},[load]);
  const update=(key:string,value:string)=>search.update({[key]:value||null});
  const negativeHref=`/admin/feedback?${contractSearch({...filters,negativeOnly:true})}`;
  return <><div className="page-header"><div><p className="eyebrow">Server-calculated aggregates</p><h1>Agency analytics</h1><p>Compare response-backed scores without exposing individual passenger records.</p></div><button className="button button-secondary" disabled={loading} onClick={()=>void load()}>Refresh</button></div>
    <section className="card card-pad analytics-filters" aria-label="Analytics filters"><label className="field"><span>Submission month</span><input className="input" type="month" value={filters.month||""} onChange={e=>update("month",e.target.value)}/></label><Filter label="Driver source" value={filters.driverSource||""} onChange={v=>update("driverSource",v)} options={[["AGENCY","Agency"],["OUTSOURCED","Outsourced"]]}/><label className="field"><span>Driver ID</span><input className="input" value={filters.driverId||""} onChange={e=>update("driverId",e.target.value)} placeholder="UUID"/></label><label className="field"><span>Vendor ID</span><input className="input" value={filters.vendorId||""} onChange={e=>update("vendorId",e.target.value)} placeholder="UUID"/></label><Filter label="Category" value={filters.category||""} onChange={v=>update("category",v)} options={categories.map(value=>[value,categoryLabel(value)])}/></section>
    {error&&<><ErrorAlert message={errorMessage(error)} requestId={error.requestId}/>{error.status!==403&&<button className="button button-secondary" onClick={()=>void load()}>Try again</button>}</>}
    {!data&&!error&&<LoadingCards/>}
    {data&&<><p className="trip-meta analytics-basis">Submission-date aggregates in {data.meta.timezone} · {data.meta.month||"all history"}.</p><div className="grid-3 metric-grid"><Metric title="Overall average" score={data.overall}/>{data.negativeFeedbackThreshold===null&&data.negativeFeedbackCount===null?<section className="card stat"><span>Negative feedback</span><strong className="metric-word">Not configured</strong><small><Link className="text-link" href="/admin/settings">Configure threshold</Link></small></section>:<Link className="card stat metric-link" href={negativeHref}><span>Negative feedback</span><strong>{data.negativeFeedbackCount}</strong><small>At or below {data.negativeFeedbackThreshold} · Review records →</small></Link>}<section className="card stat"><span>Active period</span><strong className="metric-word">{data.meta.month||"All history"}</strong><small>Based on {data.meta.dateBasis.replaceAll("_"," ").toLowerCase()}</small></section></div>
      <ScoreSection title="Monthly trend" rows={data.monthlyTrend.map(row=>({key:row.month,label:row.month,score:row}))} empty="No monthly scored feedback for this filter."/>
      <ScoreSection title="Category breakdown" rows={data.categories.map(row=>({key:row.category,label:categoryLabel(row.category),score:row,onSelect:()=>update("category",row.category)}))} empty="No category scores for this filter."/>
      <ScoreSection title="Per-driver breakdown" rows={data.drivers.map(row=>({key:row.driver.id,label:row.driver.displayName,detail:row.driver.sourceType==="AGENCY"?"Agency":`Outsourced · ${row.driver.vendorName||"Vendor unavailable"}`,score:row,onSelect:()=>update("driverId",row.driver.id)}))} empty="No driver scores for this filter."/>
      <div className="grid-2 analytics-split"><ScoreSection title="Agency versus outsourced" rows={data.sources.map(row=>({key:row.sourceType,label:row.sourceType==="AGENCY"?"Agency":"Outsourced",score:row,onSelect:()=>update("driverSource",row.sourceType)}))} empty="No source comparison is available."/><ScoreSection title="Outsourced vendors" rows={data.vendors.map(row=>({key:row.vendorId,label:row.vendorName,score:row,onSelect:()=>update("vendorId",row.vendorId)}))} empty="No outsourced vendor scores are available."/></div>
    </>}
  </>;
}
function Filter({label,value,onChange,options}:{label:string;value:string;onChange:(value:string)=>void;options:string[][]}){return <label className="field"><span>{label}</span><select className="select" value={value} onChange={e=>onChange(e.target.value)}><option value="">All</option>{options.map(([key,text])=><option key={key} value={key}>{text}</option>)}</select></label>}
function Metric({title,score}:{title:string;score:ScoreSummary}){return <section className="card stat"><span>{title}</span><strong>{scoreLabel(score.averageScore)}</strong><small>{countLabel(score.responseCount,score.answerCount)}</small></section>}
type Row={key:string;label:string;detail?:string;score:ScoreSummary;onSelect?:()=>void};
function ScoreSection({title,rows,empty}:{title:string;rows:Row[];empty:string}){return <section className="card card-pad score-section"><h2 className="section-title">{title}</h2>{rows.length===0?<EmptyState title="No aggregate data">{empty}</EmptyState>:<><div className="score-chart" aria-hidden="true">{rows.map(row=><div className="score-bar" key={row.key}><span>{row.label}</span><i style={{width:`${row.score.averageScore===null?0:Math.max(0,Math.min(100,row.score.averageScore/5*100))}%`}}/><strong>{scoreLabel(row.score.averageScore)}</strong></div>)}</div><div className="table-scroll"><table className="score-table"><caption className="sr-only">{title} accessible data table</caption><thead><tr><th>Dimension</th><th>Average</th><th>Responses</th><th>Scored answers</th></tr></thead><tbody>{rows.map(row=><tr key={row.key}>{row.onSelect?<th><button className="dimension-button" onClick={row.onSelect}>{row.label}</button>{row.detail&&<small>{row.detail}</small>}</th>:<th>{row.label}{row.detail&&<small>{row.detail}</small>}</th>}<td>{scoreLabel(row.score.averageScore)}</td><td>{row.score.responseCount}</td><td>{row.score.answerCount}</td></tr>)}</tbody></table></div></>}</section>}
