"use client";

import Link from "next/link";
import { useRouter, useSearchParams } from "next/navigation";
import { useCallback, useEffect, useState, type FormEvent } from "react";
import type { AdminDriver, Booking, BookingDetail, BookingStatus, Trip, Vehicle } from "@/lib/contracts";
import { ApiError, apiRequest, errorMessage, getData, getPaginated } from "@/lib/api";
import { formatTripRange, tripStatus } from "@/lib/status";
import { listQuery, totalPages } from "@/lib/pagination";
import { useListSearchParams, usePaginatedList, PaginationControl } from "./pagination";
import { EmptyState, ErrorAlert, LoadingCards, StatusBadge } from "./ui";
import { AlertDialog } from "./alert-dialog";
import { Modal } from "./modal";
import { Combobox, type ComboboxOption } from "./combobox";
import { ShareFeedbackLinkAction } from "./share-feedback-link";

type Notice = { message:string; requestId?:string } | null;
const bookingStates:Record<BookingStatus,{label:string;tone:string}> = {
  ACTIVE:{label:"Active",tone:"success"}, COMPLETED:{label:"Completed",tone:"neutral"},
  CANCELLED:{label:"Cancelled",tone:"danger"}, ARCHIVED:{label:"Archived",tone:"neutral"},
};
const notice = (cause:unknown) => ({ message:errorMessage(cause), requestId:cause instanceof ApiError ? cause.requestId : undefined });
const localDateTime = (iso:string) => { const date=new Date(iso); return new Date(date.getTime()-date.getTimezoneOffset()*60_000).toISOString().slice(0,16); };
const iso = (value:FormDataEntryValue|null) => { const date=new Date(String(value||"")); return Number.isNaN(date.getTime()) ? "" : date.toISOString(); };

export function AdminBookings() {
  const search=useListSearchParams();
  const allowed:BookingStatus[]=["ACTIVE","COMPLETED","CANCELLED","ARCHIVED"];
  const requested=search.parameters.get("status") as BookingStatus|null;
  const status=requested&&allowed.includes(requested)?requested:"ACTIVE";
  const list=usePaginatedList<Booking>(search.ready?`/api/v1/admin/bookings?${listQuery({status,page:search.page,pageSize:search.pageSize})}`:null);
  useEffect(()=>{if(!list.pagination)return;const last=Math.max(1,totalPages(list.pagination.total,list.pagination.pageSize));if(search.page>last)search.setPage(last,last)},[list.pagination,search.page]); // eslint-disable-line react-hooks/exhaustive-deps
  return <>
    <div className="page-header"><div><p className="eyebrow">Passenger engagements</p><h1>Bookings</h1><p>Manage engagements that can span multiple independently assigned trips.</p></div><Link className="button" href="/admin/bookings/new">Create booking</Link></div>
    <div className="toolbar"><select className="select" style={{width:"auto"}} value={status} onChange={(event)=>search.update({status:event.target.value},true)} aria-label="Filter booking status"><option value="ACTIVE">Active</option><option value="COMPLETED">Completed</option><option value="CANCELLED">Cancelled</option><option value="ARCHIVED">Archived</option></select><button className="button button-secondary" disabled={list.loading} onClick={()=>void list.refetch()}>Refresh</button></div>
    {list.error&&<ErrorAlert {...list.error}/>} {list.items===null&&!list.error&&<LoadingCards/>}
    {list.items?.length===0&&!list.error&&<EmptyState title={`No ${status.toLowerCase()} bookings`}>Create a booking or choose another status.</EmptyState>}
    {list.items&&list.items.length>0&&<section className="card data-list" aria-busy={list.loading}><div className="data-row booking-row data-head"><span>Reference / passenger</span><span>Booking period</span><span>Status / trips</span><span>Actions</span></div>{list.items.map((booking)=>{const state=bookingStates[booking.status];return <div className="data-row booking-row" key={booking.id}><span><Link className="text-link" href={`/admin/bookings/detail?bookingId=${encodeURIComponent(booking.id)}`}><strong>{booking.bookingReference}</strong></Link><small>{booking.passengerName}</small></span><span>{formatTripRange(booking.startsAt,booking.endsAt)}</span><span><StatusBadge {...state}/><small>{booking.tripCount} trip{booking.tripCount===1?"":"s"}</small></span><span className="trip-actions"><Link className="button button-secondary" href={`/admin/bookings/detail?bookingId=${encodeURIComponent(booking.id)}`}>View</Link>{booking.status!=="ARCHIVED"&&<Link className="button button-secondary" href={`/admin/bookings/edit?bookingId=${encodeURIComponent(booking.id)}`}>Edit</Link>}</span></div>})}</section>}
    {list.pagination&&<PaginationControl {...list.pagination} page={search.page} loading={list.loading} onPageChange={(page)=>search.setPage(page,totalPages(list.pagination!.total,list.pagination!.pageSize))} onPageSizeChange={search.setPageSize}/>} 
  </>;
}

export function BookingCreate() { return <BookingForm mode="create"/>; }
export function BookingEditRoute() {
  const id=useSearchParams().get("bookingId")?.trim();
  const [booking,setBooking]=useState<Booking|null>(null); const [error,setError]=useState<Notice>(null);
  useEffect(()=>{if(!id)return;void getData<BookingDetail>(`/api/v1/admin/bookings/${encodeURIComponent(id)}`).then(setBooking).catch((cause)=>setError(notice(cause)))},[id]);
  if(!id)return <EmptyState title="Choose a booking">Open a booking from the list before editing it.</EmptyState>;
  if(error)return <ErrorAlert {...error}/>; if(!booking)return <LoadingCards/>;
  return <BookingForm mode="edit" booking={booking}/>;
}

function BookingForm({mode,booking}:{mode:"create"|"edit";booking?:Booking}) {
  const router=useRouter(); const [busy,setBusy]=useState(false); const [error,setError]=useState<Notice>(null); const [periodError,setPeriodError]=useState("");
  async function submit(event:FormEvent<HTMLFormElement>){event.preventDefault();if(busy)return;const data=new FormData(event.currentTarget);const startsAt=iso(data.get("startsAt"));const endsAt=iso(data.get("endsAt"));if(!startsAt||!endsAt||Date.parse(endsAt)<=Date.parse(startsAt)){setPeriodError("Booking end must be after its start.");return}setBusy(true);setError(null);setPeriodError("");const body={bookingReference:String(data.get("bookingReference")||"").trim(),passengerName:String(data.get("passengerName")||"").trim(),startsAt,endsAt,notes:String(data.get("notes")||"").trim()||null};try{const saved=await getData<Booking>(mode==="create"?"/api/v1/admin/bookings":`/api/v1/admin/bookings/${booking!.id}`,{method:mode==="create"?"POST":"PATCH",body:JSON.stringify(body)});router.push(`/admin/bookings/detail?bookingId=${encodeURIComponent(saved.id)}`)}catch(cause){setError(notice(cause))}finally{setBusy(false)}}
  return <><Link className="text-link feedback-back" href={booking?`/admin/bookings/detail?bookingId=${encodeURIComponent(booking.id)}`:"/admin/bookings"}>← {booking?"Back to booking":"Back to bookings"}</Link><div className="page-header"><div><p className="eyebrow">{mode==="create"?"New engagement":"Booking management"}</p><h1>{mode==="create"?"Create booking":`Edit ${booking!.bookingReference}`}</h1><p>Set the overall passenger engagement period. Trips must remain inside this window.</p></div></div><form className="card card-pad booking-form" onSubmit={submit}>{error&&<ErrorAlert {...error}/>}<div className="grid-2"><Field name="bookingReference" label="Booking reference" maxLength={100} defaultValue={booking?.bookingReference}/><Field name="passengerName" label="Passenger name" maxLength={200} defaultValue={booking?.passengerName}/></div><div className="grid-2"><Field name="startsAt" label="Booking starts" type="datetime-local" defaultValue={booking?localDateTime(booking.startsAt):undefined}/><Field name="endsAt" label="Booking ends" type="datetime-local" defaultValue={booking?localDateTime(booking.endsAt):undefined} error={periodError}/></div><div className="field"><label htmlFor="notes">Notes (optional)</label><textarea className="textarea" id="notes" name="notes" maxLength={2000} defaultValue={booking?.notes||""}/></div><div className="dialog-actions"><Link className="button button-secondary" href={booking?`/admin/bookings/detail?bookingId=${encodeURIComponent(booking.id)}`:"/admin/bookings"}>Cancel</Link><button className="button" disabled={busy}>{busy?"Saving…":mode==="create"?"Create booking":"Save changes"}</button></div></form></>;
}

export function BookingDetailRoute() {
  const id=useSearchParams().get("bookingId")?.trim();
  return id?<BookingDetailView bookingId={id}/>:<EmptyState title="Choose a booking">Open a booking from the list to view it.</EmptyState>;
}

function BookingDetailView({bookingId}:{bookingId:string}) {
  const [booking,setBooking]=useState<BookingDetail|null>(null); const [error,setError]=useState<Notice>(null); const [busy,setBusy]=useState(false); const [archiveOpen,setArchiveOpen]=useState(false); const [adding,setAdding]=useState(false);
  const load=useCallback(async()=>{setError(null);try{setBooking(await getData<BookingDetail>(`/api/v1/admin/bookings/${encodeURIComponent(bookingId)}`))}catch(cause){setError(notice(cause))}},[bookingId]);
  useEffect(()=>{queueMicrotask(()=>void load())},[load]);
  async function update(status:"ACTIVE"|"COMPLETED"|"CANCELLED"){setBusy(true);try{await apiRequest(`/api/v1/admin/bookings/${bookingId}`,{method:"PATCH",body:JSON.stringify({status})});await load()}catch(cause){setError(notice(cause))}finally{setBusy(false)}}
  async function archive(){setBusy(true);try{await apiRequest(`/api/v1/admin/bookings/${bookingId}/archive`,{method:"POST"});setArchiveOpen(false);await load()}catch(cause){setError(notice(cause))}finally{setBusy(false)}}
  if(error&&!booking)return <><ErrorAlert {...error}/><button className="button button-secondary" onClick={()=>void load()}>Try again</button></>;if(!booking)return <LoadingCards/>;const state=bookingStates[booking.status];
  return <><Link className="text-link feedback-back" href="/admin/bookings">← Back to bookings</Link><div className="page-header"><div><p className="eyebrow">Passenger engagement</p><h1>{booking.bookingReference}</h1><p>{booking.passengerName} · {formatTripRange(booking.startsAt,booking.endsAt)}</p></div><StatusBadge {...state}/></div>{error&&<ErrorAlert {...error}/>}<div className="toolbar detail-actions">{booking.status==="ACTIVE"&&<button className="button" disabled={busy} onClick={()=>setAdding(true)}>Add trip</button>}{booking.status!=="ARCHIVED"&&<Link className="button button-secondary" href={`/admin/bookings/edit?bookingId=${encodeURIComponent(booking.id)}`}>Edit booking</Link>}{booking.status==="ACTIVE"&&<><button className="button button-secondary" disabled={busy} onClick={()=>void update("COMPLETED")}>Mark completed</button><button className="button button-secondary" disabled={busy} onClick={()=>void update("CANCELLED")}>Cancel booking</button></>}{(booking.status==="COMPLETED"||booking.status==="CANCELLED")&&<button className="button button-secondary" disabled={busy} onClick={()=>void update("ACTIVE")}>Reactivate</button>}{booking.status!=="ARCHIVED"&&<button className="button button-danger" disabled={busy} onClick={()=>setArchiveOpen(true)}>Archive</button>}</div><div className="grid-3 booking-summary"><section className="card stat"><span>Passenger</span><strong>{booking.passengerName}</strong><small>Booking contact</small></section><section className="card stat"><span>Trips</span><strong>{booking.tripCount}</strong><small>Across this engagement</small></section><section className="card stat"><span>Notes</span><strong className="booking-note">{booking.notes||"—"}</strong><small>{booking.notes?"Internal booking notes":"No notes supplied"}</small></section></div><section className="booking-trips"><div className="section-heading"><div><p className="eyebrow">Chronological itinerary</p><h2 className="section-title">Trips</h2></div></div>{booking.trips.length===0?<EmptyState title="No trips yet">{booking.status==="ACTIVE"?"Add the first trip to this booking.":"No trips were added to this booking."}</EmptyState>:<div className="trip-list">{booking.trips.map((trip)=><BookingTrip key={trip.id} trip={trip}/>)}</div>}</section>{adding&&<Modal onDismiss={()=>!busy&&setAdding(false)}><AddTrip booking={booking} onSaved={async()=>{setAdding(false);await load()}} onCancel={()=>setAdding(false)}/></Modal>}{archiveOpen&&<AlertDialog title={`Archive ${booking.bookingReference}?`} confirmLabel="Archive booking" destructive busy={busy} onCancel={()=>setArchiveOpen(false)} onConfirm={()=>void archive()}><p>The booking and its history will remain available in archived views.</p></AlertDialog>}</>;
}

function BookingTrip({trip}:{trip:Trip}) { const state=tripStatus[trip.status];return <article className="card trip-card"><div className="trip-card-head"><div><span className="eyebrow">{formatTripRange(trip.scheduledAt,trip.scheduledEndAt)}</span><h3>{trip.pickupLocation} → {trip.destination}</h3><span className="trip-meta">{trip.driver.displayName} · {trip.driver.driverCode} · {trip.vehicle.displayName} · {trip.vehicle.registrationNumber}</span></div><StatusBadge {...state}/></div>{(trip.status==="READY"||trip.status==="FEEDBACK_STARTED")&&<div className="trip-actions"><ShareFeedbackLinkAction tripId={trip.id} audience="admin"/></div>}</article> }

function AddTrip({booking,onSaved,onCancel}:{booking:BookingDetail;onSaved:()=>void;onCancel:()=>void}) {
  const [drivers,setDrivers]=useState<AdminDriver[]>([]);const [vehicles,setVehicles]=useState<Vehicle[]>([]);const [busy,setBusy]=useState(false);const [error,setError]=useState<Notice>(null);const [periodError,setPeriodError]=useState("");
  useEffect(()=>{void Promise.all([getPaginated<AdminDriver>("/api/v1/admin/drivers?status=ACTIVE&page=1&pageSize=100"),getPaginated<Vehicle>("/api/v1/admin/vehicles?status=ACTIVE&page=1&pageSize=100")]).then(([d,v])=>{setDrivers(d.data);setVehicles(v.data)}).catch((cause)=>setError(notice(cause)))},[]);
  const driverOptions:ComboboxOption[]=drivers.map((driver)=>({value:driver.id,label:driver.displayName,description:`${driver.driverCode} · ${driver.sourceType==="AGENCY"?"Agency":driver.vendorName||"Outsourced"}`,disabled:!driver.assignmentEnabled}));
  const vehicleOptions:ComboboxOption[]=vehicles.map((vehicle)=>({value:vehicle.id,label:vehicle.displayName,description:vehicle.registrationNumber,keywords:vehicle.registrationNumber}));
  async function submit(event:FormEvent<HTMLFormElement>){event.preventDefault();const data=new FormData(event.currentTarget);const scheduledAt=iso(data.get("scheduledAt"));const scheduledEndAt=iso(data.get("scheduledEndAt"));if(!scheduledAt||!scheduledEndAt||Date.parse(scheduledEndAt)<=Date.parse(scheduledAt)||Date.parse(scheduledAt)<Date.parse(booking.startsAt)||Date.parse(scheduledEndAt)>Date.parse(booking.endsAt)){setPeriodError("Trip start and end must be ordered and fall within the booking period.");return}setBusy(true);setError(null);try{await apiRequest("/api/v1/admin/trips",{method:"POST",body:JSON.stringify({bookingId:booking.id,pickupLocation:String(data.get("pickupLocation")||"").trim(),destination:String(data.get("destination")||"").trim(),scheduledAt,scheduledEndAt,driverId:String(data.get("driverId")||""),vehicleId:String(data.get("vehicleId")||"")})});await onSaved()}catch(cause){setError(notice(cause))}finally{setBusy(false)}}
  return <form className="dialog dialog-wide" role="dialog" aria-modal="true" onSubmit={submit}><p className="eyebrow">{booking.bookingReference}</p><h2>Add a trip</h2><p className="trip-meta">{booking.passengerName} · booking window {formatTripRange(booking.startsAt,booking.endsAt)}</p>{error&&<ErrorAlert {...error}/>}<div className="field"><label>Booking</label><input className="input input-readonly" value={`${booking.bookingReference} · ${booking.passengerName}`} readOnly/></div><div className="grid-2"><Field name="pickupLocation" label="Pickup location" maxLength={500}/><Field name="destination" label="Destination" maxLength={500}/></div><div className="grid-2"><Field name="scheduledAt" label="Trip starts" type="datetime-local" min={localDateTime(booking.startsAt)} max={localDateTime(booking.endsAt)}/><Field name="scheduledEndAt" label="Trip ends" type="datetime-local" min={localDateTime(booking.startsAt)} max={localDateTime(booking.endsAt)} error={periodError}/></div><Combobox id="driverId" name="driverId" label="Active driver" options={driverOptions} placeholder="Search drivers" emptyMessage="No drivers match" required/><Combobox id="vehicleId" name="vehicleId" label="Active vehicle" options={vehicleOptions} placeholder="Search vehicles" emptyMessage="No vehicles match" required/><div className="dialog-actions"><button type="button" className="button button-secondary" disabled={busy} onClick={onCancel}>Cancel</button><button className="button" disabled={busy}>{busy?"Creating…":"Create trip"}</button></div></form>;
}

function Field({name,label,type="text",required=true,error,...rest}:{name:string;label:string;type?:string;required?:boolean;error?:string;[key:string]:unknown}) { return <div className="field"><label htmlFor={name}>{label}</label><input className="input" id={name} name={name} type={type} required={required} aria-invalid={!!error} {...rest}/>{error&&<small className="field-error">{error}</small>}</div> }
