"use client";
import { FormEvent,useCallback,useEffect,useState } from "react";
import type { AdminDriver,LifecycleStatus,Paginated,Vehicle,Vendor } from "@/lib/contracts";
import { ApiError,apiRequest,errorMessage } from "@/lib/api";
import { lifecycleStatus } from "@/lib/status";
import { EmptyState,ErrorAlert,LoadingCards,StatusBadge } from "./ui";

type Resource="vendors"|"vehicles"|"drivers";type Item=Vendor|Vehicle|AdminDriver;
const titles={vendors:["Vendors","Manage the companies that supply outsourced drivers."],vehicles:["Vehicles","Maintain the active fleet used when trips are created."],drivers:["Drivers","Manage agency and outsourced drivers and their account lifecycle."]} as const;
function primary(item:Item){return "name" in item?item.name:"registrationNumber" in item?item.displayName:item.displayName}
function secondary(item:Item){return "contactName" in item?(item.contactName||item.contactEmail||"No contact details"):"registrationNumber" in item?item.registrationNumber:`${item.driverCode} · ${item.sourceType==="OUTSOURCED"?(item.vendorName||"Vendor required"):"Agency driver"}`}

export function AdminResources({resource}:{resource:Resource}){const [items,setItems]=useState<Item[]|null>(null);const [status,setStatus]=useState<LifecycleStatus>("ACTIVE");const [error,setError]=useState<{message:string;requestId?:string}|null>(null);const [showForm,setShowForm]=useState(false);const [busy,setBusy]=useState(false);const [vendors,setVendors]=useState<Vendor[]>([]);
  const load=useCallback(async()=>{setError(null);try{const response=await apiRequest<Paginated<Item>>(`/api/v1/admin/${resource}?status=${status}&page=1&pageSize=50`);setItems(response.data);if(resource==="drivers"){const vr=await apiRequest<Paginated<Vendor>>("/api/v1/admin/vendors?status=ACTIVE&page=1&pageSize=100");setVendors(vr.data)}}catch(cause){setItems([]);setError({message:errorMessage(cause),requestId:cause instanceof ApiError?cause.requestId:undefined})}},[resource,status]);
  useEffect(()=>{queueMicrotask(()=>void load())},[load]);
  async function create(event:FormEvent<HTMLFormElement>){event.preventDefault();setBusy(true);setError(null);const data=new FormData(event.currentTarget);let body:Record<string,unknown>;if(resource==="vendors")body={name:data.get("name"),contactName:data.get("contactName")||undefined,contactEmail:data.get("contactEmail")||undefined,contactPhone:data.get("contactPhone")||undefined};else if(resource==="vehicles")body={displayName:data.get("displayName"),registrationNumber:data.get("registrationNumber")};else{const sourceType=data.get("sourceType");body={displayName:data.get("displayName"),email:data.get("email"),password:data.get("password"),driverCode:data.get("driverCode"),phone:data.get("phone")||undefined,sourceType,vendorId:sourceType==="OUTSOURCED"?data.get("vendorId"):null}}try{await apiRequest(`/api/v1/admin/${resource}`,{method:"POST",body:JSON.stringify(body)});setShowForm(false);await load()}catch(cause){setError({message:errorMessage(cause),requestId:cause instanceof ApiError?cause.requestId:undefined})}finally{setBusy(false)}}
  async function changeStatus(item:Item,next:LifecycleStatus){setBusy(true);try{await apiRequest(`/api/v1/admin/${resource}/${item.id}/status`,{method:"PATCH",body:JSON.stringify({status:next})});await load()}catch(cause){setError({message:errorMessage(cause),requestId:cause instanceof ApiError?cause.requestId:undefined})}finally{setBusy(false)}}
  const [title,copy]=titles[resource];return <><div className="page-header"><div><p className="eyebrow">Operations directory</p><h1>{title}</h1><p>{copy}</p></div><button className="button" onClick={()=>setShowForm(true)}>Add {resource.slice(0,-1)}</button></div><div className="toolbar"><div className="filters"><label className="field" style={{margin:0}}><span className="sr-only">Filter by lifecycle</span><select className="select" value={status} onChange={e=>setStatus(e.target.value as LifecycleStatus)}><option value="ACTIVE">Active</option><option value="DEACTIVATED">Deactivated</option><option value="ARCHIVED">Archived</option></select></label></div><button className="button button-secondary" onClick={load}>Refresh</button></div>{error&&<ErrorAlert message={error.message} requestId={error.requestId}/>} {items===null&&<LoadingCards/>}{items?.length===0&&!error&&<EmptyState title={`No ${status.toLowerCase()} ${resource}`}>Create the first record or choose another lifecycle filter.</EmptyState>}{items&&items.length>0&&<section className="card data-list"><div className="data-row data-head"><span>Name</span><span>Details</span><span>Status</span><span>Actions</span></div>{items.map(item=>{const state=lifecycleStatus[item.status];return <div className="data-row" key={item.id}><span><strong>{primary(item)}</strong><small>{"email" in item?item.email:"contactEmail" in item?item.contactEmail:"Fleet record"}</small></span><span>{secondary(item)}</span><StatusBadge label={state.label} tone={state.tone}/><span>{item.status==="ACTIVE"?<button className="button button-secondary" disabled={busy} onClick={()=>changeStatus(item,"DEACTIVATED")}>Deactivate</button>:item.status==="DEACTIVATED"?<><button className="button button-secondary" disabled={busy} onClick={()=>changeStatus(item,"ACTIVE")}>Activate</button> <button className="button button-secondary" disabled={busy} onClick={()=>changeStatus(item,"ARCHIVED")}>Archive</button></>:<span className="trip-meta">Read-only history</span>}</span></div>})}</section>}
    {showForm&&<div className="dialog-backdrop"><form className="dialog" role="dialog" aria-modal="true" onSubmit={create}><span className="eyebrow">New {resource.slice(0,-1)}</span><h2>Add to operations</h2>{resource==="vendors"&&<><Field name="name" label="Vendor name" maxLength={200}/><Field name="contactName" label="Contact name" maxLength={200} required={false}/><Field name="contactEmail" label="Contact email" type="email" maxLength={320} required={false}/><Field name="contactPhone" label="Contact phone" maxLength={32} required={false}/></>}{resource==="vehicles"&&<><Field name="displayName" label="Vehicle display name" maxLength={200}/><Field name="registrationNumber" label="Registration number" maxLength={64}/></>}{resource==="drivers"&&<><Field name="displayName" label="Driver name" maxLength={200}/><Field name="email" label="Email" type="email" maxLength={320}/><Field name="driverCode" label="Driver code" maxLength={64}/><Field name="phone" label="Phone" maxLength={32} required={false}/><Field name="password" label="Temporary password" type="password" minLength={12} maxLength={128}/><div className="field"><label htmlFor="sourceType">Driver source</label><select className="select" name="sourceType" id="sourceType"><option value="AGENCY">Agency</option><option value="OUTSOURCED">Outsourced</option></select><small>Choose a vendor below for outsourced drivers.</small></div><div className="field"><label htmlFor="vendorId">Vendor</label><select className="select" name="vendorId" id="vendorId"><option value="">No vendor</option>{vendors.map(v=><option key={v.id} value={v.id}>{v.name}</option>)}</select></div></> }<div className="dialog-actions"><button type="button" className="button button-secondary" onClick={()=>setShowForm(false)}>Cancel</button><button className="button" disabled={busy}>{busy?"Saving…":"Create record"}</button></div></form></div>}
  </>;
}
function Field({name,label,type="text",required=true,...rest}:{name:string;label:string;type?:string;required?:boolean;maxLength?:number;minLength?:number}){return <div className="field"><label htmlFor={name}>{label}{!required&&" (optional)"}</label><input className="input" id={name} name={name} type={type} required={required} {...rest}/></div>}
