"use client";
import { FormEvent,useCallback,useEffect,useState } from "react";
import type { AdminDriver,Paginated,Trip,TripStatus,Vehicle } from "@/lib/contracts";
import { ApiError,apiRequest,errorMessage } from "@/lib/api";
import { formatIndiaDate,tripSource,tripStatus } from "@/lib/status";
import { EmptyState,ErrorAlert,LoadingCards,StatusBadge } from "./ui";

export function AdminTrips(){const [items,setItems]=useState<Trip[]|null>(null);const [drivers,setDrivers]=useState<AdminDriver[]>([]);const [vehicles,setVehicles]=useState<Vehicle[]>([]);const [status,setStatus]=useState<TripStatus>("READY");const [show,setShow]=useState(false);const [busy,setBusy]=useState(false);const [error,setError]=useState<{message:string;requestId?:string}|null>(null);
  const load=useCallback(async()=>{setError(null);try{const [trips,driverList,vehicleList]=await Promise.all([apiRequest<Paginated<Trip>>(`/api/v1/admin/trips?status=${status}&page=1&pageSize=50`),apiRequest<Paginated<AdminDriver>>("/api/v1/admin/drivers?status=ACTIVE&page=1&pageSize=100"),apiRequest<Paginated<Vehicle>>("/api/v1/admin/vehicles?status=ACTIVE&page=1&pageSize=100")]);setItems(trips.data);setDrivers(driverList.data);setVehicles(vehicleList.data)}catch(cause){setItems([]);setError({message:errorMessage(cause),requestId:cause instanceof ApiError?cause.requestId:undefined})}},[status]);
  useEffect(()=>{queueMicrotask(()=>void load())},[load]);
  async function create(event:FormEvent<HTMLFormElement>){event.preventDefault();setBusy(true);const d=new FormData(event.currentTarget);try{await apiRequest("/api/v1/admin/trips",{method:"POST",body:JSON.stringify({bookingReference:d.get("bookingReference"),passengerName:d.get("passengerName"),pickupLocation:d.get("pickupLocation"),destination:d.get("destination"),scheduledAt:new Date(String(d.get("scheduledAt"))).toISOString(),vehicleId:d.get("vehicleId"),driverId:d.get("driverId")})});setShow(false);await load()}catch(cause){setError({message:errorMessage(cause),requestId:cause instanceof ApiError?cause.requestId:undefined})}finally{setBusy(false)}}
  async function archive(id:string){if(!confirm("Archive this trip? It will remain in historical records."))return;setBusy(true);try{await apiRequest(`/api/v1/admin/trips/${id}/archive`,{method:"POST"});await load()}catch(cause){setError({message:errorMessage(cause),requestId:cause instanceof ApiError?cause.requestId:undefined})}finally{setBusy(false)}}
  return <><div className="page-header"><div><p className="eyebrow">Journey operations</p><h1>Trips</h1><p>Create and assign trips using active drivers and vehicles. Only ready trips may be edited.</p></div><button className="button" onClick={()=>setShow(true)}>Create assigned trip</button></div><div className="toolbar"><select className="select" style={{width:"auto"}} value={status} onChange={e=>setStatus(e.target.value as TripStatus)} aria-label="Filter trip status"><option value="READY">Ready for feedback</option><option value="FEEDBACK_STARTED">Feedback started</option><option value="SUBMITTED">Feedback received</option><option value="ARCHIVED">Archived</option></select><button className="button button-secondary" onClick={load}>Refresh</button></div>{error&&<ErrorAlert message={error.message} requestId={error.requestId}/>} {items===null&&<LoadingCards/>}{items?.length===0&&!error&&<EmptyState title="No trips match this view">Create a journey or choose another feedback status.</EmptyState>}{items&&items.length>0&&<section className="trip-list">{items.map(trip=>{const state=tripStatus[trip.status];return <article className="card trip-card" key={trip.id}><div className="trip-card-head"><div><span className="eyebrow">{tripSource[trip.creationSource]}</span><h3>{trip.bookingReference}</h3><span className="trip-meta">{formatIndiaDate(trip.scheduledAt)} · {trip.driver.displayName} · {trip.vehicle.displayName}</span></div><StatusBadge label={state.label} tone={state.tone}/></div><div className="route"><div className="route-line"><i className="route-dot"/><i className="route-dot"/></div><div className="route-points"><span><small>Pickup</small>{trip.pickupLocation}</span><span><small>Destination</small>{trip.destination}</span></div></div>{trip.status!=="ARCHIVED"&&<button className="button button-secondary" disabled={busy} onClick={()=>archive(trip.id)}>Archive trip</button>}</article>})}</section>}
  {show&&<div className="dialog-backdrop"><form className="dialog" onSubmit={create} role="dialog" aria-modal="true"><span className="eyebrow">Admin-assigned</span><h2>Create a trip</h2><TripField name="bookingReference" label="Booking reference" maxLength={100}/><TripField name="passengerName" label="Passenger name" maxLength={200}/><TripField name="pickupLocation" label="Pickup location" maxLength={500}/><TripField name="destination" label="Destination" maxLength={500}/><TripField name="scheduledAt" label="Scheduled date and time" type="datetime-local"/><div className="field"><label htmlFor="driverId">Active driver</label><select className="select" name="driverId" id="driverId" required><option value="">Select a driver</option>{drivers.map(d=><option value={d.id} key={d.id}>{d.displayName} · {d.driverCode}</option>)}</select></div><div className="field"><label htmlFor="vehicleId">Active vehicle</label><select className="select" name="vehicleId" id="vehicleId" required><option value="">Select a vehicle</option>{vehicles.map(v=><option value={v.id} key={v.id}>{v.displayName} · {v.registrationNumber}</option>)}</select></div><div className="dialog-actions"><button type="button" className="button button-secondary" onClick={()=>setShow(false)}>Cancel</button><button className="button" disabled={busy}>{busy?"Creating…":"Create trip"}</button></div></form></div>}
  </>;
}
function TripField({name,label,type="text",maxLength}:{name:string;label:string;type?:string;maxLength?:number}){return <div className="field"><label htmlFor={name}>{label}</label><input className="input" id={name} name={name} type={type} maxLength={maxLength} required/></div>}
