"use client";

import { useCallback, useEffect, useMemo, useState } from "react";
import { useRouter } from "next/navigation";
import type { AdminFeedbackAnswer, AdminFeedbackDetail, AdminFeedbackSummary, AgencySettings, FeedbackReviewState } from "@/lib/contracts";
import { ApiError, apiRequest, errorMessage, getData } from "@/lib/api";
import { categoryLabel, formatInTimezone, invalidateCaches, scoreLabel } from "@/lib/feedback-contract";
import { ErrorAlert, LoadingCards, StatusBadge } from "./ui";
import { Modal } from "./modal";

export function AdminFeedbackDetailView({feedbackId}:{feedbackId:string}){
  const router=useRouter(); const [detail,setDetail]=useState<AdminFeedbackDetail|null>(null); const [timezone,setTimezone]=useState("Asia/Kolkata");
  const [error,setError]=useState<ApiError|null>(null); const [loading,setLoading]=useState(true); const [action,setAction]=useState<FeedbackReviewState|null>(null); const [reason,setReason]=useState(""); const [busy,setBusy]=useState(false); const [actionError,setActionError]=useState("");
  const load=useCallback(async()=>{setLoading(true);setError(null);try{const [value,settings]=await Promise.all([getData<AdminFeedbackDetail>(`/api/v1/admin/feedback/${encodeURIComponent(feedbackId)}`),getData<AgencySettings>("/api/v1/admin/settings").catch(()=>null)]);setDetail(value);if(settings)setTimezone(settings.timezone)}catch(cause){setError(cause instanceof ApiError?cause:new ApiError(0,"NETWORK_UNAVAILABLE",errorMessage(cause)))}finally{setLoading(false)}},[feedbackId]);
  useEffect(()=>{queueMicrotask(()=>void load())},[load]);
  const answers=useMemo(()=>[...(detail?.answers||[])].sort((a,b)=>a.displayOrder-b.displayOrder),[detail]);
  async function mutate(){if(!detail||!action)return;if(action==="ARCHIVED"&&!reason.trim()){setActionError("An archive reason is required.");return}if(action==="ARCHIVED"&&!window.confirm("Archive this feedback? It will be excluded from analytics and cannot be restored."))return;setBusy(true);setActionError("");try{const response=await apiRequest<{data:AdminFeedbackSummary}>(`/api/v1/admin/feedback/${encodeURIComponent(feedbackId)}/review-state`,{method:"PATCH",body:JSON.stringify({state:action,...(reason.trim()?{reason:reason.trim()}:{})})});setDetail(current=>current?{...current,...response.data}:current);setAction(null);setReason("");invalidateCaches(["feedback-detail","feedback-lists","analytics","driver-performance"]);await load()}catch(cause){const code=cause instanceof ApiError?cause.code:"";if(cause instanceof ApiError&&code==="FEEDBACK_NOT_FOUND"){setAction(null);setError(cause)}else setActionError(code==="FEEDBACK_ARCHIVE_REASON_REQUIRED"?"An archive reason is required.":code==="FEEDBACK_REVIEW_TRANSITION_INVALID"?"That review action is no longer valid. Refresh and review the current state.":code==="FEEDBACK_RESTORE_NOT_SUPPORTED"?"Archived feedback cannot be restored.":errorMessage(cause))}finally{setBusy(false)}}
  if(loading&&!detail)return <LoadingCards/>;
  if(error?.code==="FEEDBACK_NOT_FOUND"||error?.status===404)return <div className="card empty"><h1>Feedback not found</h1><p>This record may no longer be available.</p><button className="button button-secondary" onClick={()=>router.back()}>Back to feedback</button></div>;
  if(error?.status===403)return <div className="alert" role="alert"><strong>Admin access required.</strong><div>Your account cannot inspect passenger feedback.</div></div>;
  if(!detail)return <>{error&&<ErrorAlert message={errorMessage(error)} requestId={error.requestId}/>}<button className="button button-secondary" onClick={()=>void load()}>Try again</button></>;
  const archived=detail.reviewState==="ARCHIVED";
  return <><button className="button button-secondary feedback-back" onClick={()=>router.back()}>← Back to filtered feedback</button><div className="page-header"><div><p className="eyebrow">Immutable response</p><h1>Feedback detail</h1><p>Booking {detail.bookingReference} · submitted {formatInTimezone(detail.submittedAt,timezone)}</p></div><StatusBadge label={detail.reviewState==="NORMAL"?"Normal":detail.reviewState==="FLAGGED"?"Flagged":"Archived"} tone={detail.reviewState==="FLAGGED"?"warning":archived?"neutral":"success"}/></div>
    {error&&<ErrorAlert message={errorMessage(error)} requestId={error.requestId}/>}
    <section className="grid-3 feedback-detail-summary"><div className="card stat"><span>Overall score</span><strong>{scoreLabel(detail.overallScore)}</strong><small>Immutable scored-answer average</small></div><div className="card stat"><span>Submission mode</span><strong className="metric-word">{detail.submissionMode==="OFFLINE_SYNC"?"Offline sync":"Online"}</strong><small>Received {formatInTimezone(detail.receivedAt,timezone)}</small></div><div className="card stat"><span>Review state</span><strong className="metric-word">{detail.reviewState.toLowerCase()}</strong><small>{archived?"Read-only; restore is not supported":"Administrative state only"}</small></div></section>
    {!archived&&<div className="trip-actions detail-actions">{detail.reviewState==="NORMAL"?<button className="button button-secondary" onClick={()=>setAction("FLAGGED")}>Flag feedback</button>:<button className="button button-secondary" onClick={()=>setAction("NORMAL")}>Unflag feedback</button>}<button className="button button-danger" onClick={()=>setAction("ARCHIVED")}>Archive feedback</button></div>}
    <div className="grid-2 detail-grid"><section className="card card-pad"><h2 className="section-title">Respondent and booking</h2><Definition items={[["Name",detail.respondent.name],["Phone",detail.respondent.phone],["Email",detail.respondent.email],["Booking reference",detail.respondent.bookingReference]]}/></section><section className="card card-pad"><h2 className="section-title">Trip snapshot</h2><Definition items={[["Route",`${detail.trip.pickupLocation} → ${detail.trip.destination}`],["Schedule",`${formatInTimezone(detail.trip.scheduledAt,timezone)} – ${formatInTimezone(detail.trip.scheduledEndAt,timezone)}`],["Vehicle",`${detail.trip.vehicle.displayName} · ${detail.trip.vehicle.registrationNumber}`],["Driver",detail.driver.displayName],["Source",detail.driver.sourceType==="AGENCY"?"Agency":`Outsourced · ${detail.driver.vendorName||"Vendor unavailable"}`]]}/></section></div>
    <section className="card card-pad feedback-answers"><h2 className="section-title">Answers</h2><p className="trip-meta">Submitted answers are immutable.</p>{answers.map(answer=><article key={answer.id} className="answer-row"><header><span className="eyebrow">{categoryLabel(answer.category)} · {answer.questionType.replaceAll("_"," ").toLowerCase()}</span>{answer.numericScore!==null&&<strong>{answer.numericScore.toFixed(2)} scored</strong>}</header><h3>{answer.prompt}</h3><AnswerValue answer={answer}/></article>)}</section>
    <div className="grid-2 detail-grid"><section className="card card-pad"><h2 className="section-title">Review history</h2>{detail.reviewHistory.length===0?<p>No administrative review actions.</p>:<ol className="history-list">{detail.reviewHistory.map(event=><li key={event.id}><strong>{event.action.toLowerCase()}</strong> by {event.performedBy.displayName}<small>{formatInTimezone(event.createdAt,timezone)}{event.reason?` · ${event.reason}`:" · No reason supplied"}</small></li>)}</ol>}</section><details className="card card-pad technical-details"><summary>Technical details</summary><Definition items={[["Consent version",detail.consentVersionId],["Consented at",formatInTimezone(detail.consentedAt,timezone)],["Questionnaire version",detail.questionnaireVersionId]]}/></details></div>
    {action&&<Modal onDismiss={()=>setAction(null)}><section className="dialog" role="dialog" aria-modal="true" aria-labelledby="review-title"><p className="eyebrow">Review action</p><h2 id="review-title">{action==="FLAGGED"?"Flag feedback":action==="NORMAL"?"Unflag feedback":"Archive feedback"}</h2><p>{action==="ARCHIVED"?"Archiving excludes this feedback from aggregates and cannot be reversed.":"This changes only the administrative review state; submitted answers remain unchanged."}</p><div className="field"><label htmlFor="review-reason">Reason {action==="ARCHIVED"?"(required)":"(optional)"}</label><textarea id="review-reason" className="textarea" maxLength={1000} value={reason} onChange={e=>setReason(e.target.value)} aria-invalid={!!actionError}/>{actionError&&<small className="field-error" role="alert">{actionError}</small>}</div><div className="dialog-actions"><button className="button button-secondary" onClick={()=>setAction(null)}>Cancel</button><button className={action==="ARCHIVED"?"button button-danger":"button"} disabled={busy} onClick={()=>void mutate()}>{busy?"Saving…":action==="ARCHIVED"?"Archive permanently":"Confirm action"}</button></div></section></Modal>}
  </>;
}
function Definition({items}:{items:Array<[string,string]>}){return <dl className="definition-list">{items.map(([term,value])=><div key={term}><dt>{term}</dt><dd>{value}</dd></div>)}</dl>}
function AnswerValue({answer}:{answer:AdminFeedbackAnswer}){const value=answer.value;if(answer.questionType==="YES_NO"&&typeof value==="boolean")return <p>{value?"Yes":"No"}</p>;if(Array.isArray(value))return <ul>{value.map(item=><li key={String(item)}>{String(item)}</li>)}</ul>;if(["STAR_RATING","EMOJI_RATING","SINGLE_CHOICE","TEXT"].includes(answer.questionType)&&(typeof value==="string"||typeof value==="number"))return <p className={answer.questionType==="TEXT"?"answer-text":undefined}>{String(value)}</p>;return <pre className="safe-json">{safeJson(value)}</pre>}
function safeJson(value:unknown){try{return JSON.stringify(value,null,2)}catch{return "Unsupported answer value"}}
