"use client";

import { useCallback, useEffect, useMemo, useState, type FormEvent } from "react";
import type { AgencySettings, UpdateAgencySettingsRequest } from "@/lib/contracts";
import { ApiError, apiRequest, errorMessage, getData } from "@/lib/api";
import { invalidateCaches } from "@/lib/feedback-contract";
import { ErrorAlert, LoadingCards } from "./ui";

type Draft={agencyName:string;timezone:string;defaultThankYouMessage:string;negativeFeedbackThreshold:string};
const draftOf=(value:AgencySettings):Draft=>({...value,negativeFeedbackThreshold:value.negativeFeedbackThreshold===null?"":String(value.negativeFeedbackThreshold)});

export function AdminSettings(){
  const [saved,setSaved]=useState<AgencySettings|null>(null); const [draft,setDraft]=useState<Draft|null>(null);
  const [loading,setLoading]=useState(true); const [saving,setSaving]=useState(false); const [notice,setNotice]=useState("");
  const [error,setError]=useState<{message:string;requestId?:string;forbidden?:boolean}|null>(null);
  const [fields,setFields]=useState<Record<string,string>>({});
  const dirty=useMemo(()=>!!saved&&!!draft&&JSON.stringify(draft)!==JSON.stringify(draftOf(saved)),[saved,draft]);
  const load=useCallback(async(force=false)=>{if(dirty&&!force&&!window.confirm("Discard your unsaved settings changes and reload the server version?"))return;setLoading(true);setError(null);try{const value=await getData<AgencySettings>("/api/v1/admin/settings");setSaved(value);setDraft(draftOf(value))}catch(cause){setError({message:errorMessage(cause),requestId:cause instanceof ApiError?cause.requestId:undefined,forbidden:cause instanceof ApiError&&cause.status===403})}finally{setLoading(false)}},[dirty]);
  useEffect(()=>{queueMicrotask(()=>void load(true))},[]); // eslint-disable-line react-hooks/exhaustive-deps
  useEffect(()=>{const warn=(event:BeforeUnloadEvent)=>{if(dirty)event.preventDefault()};window.addEventListener("beforeunload",warn);return()=>window.removeEventListener("beforeunload",warn)},[dirty]);
  function validate(){if(!draft)return false;const next:Record<string,string>={};if(!draft.agencyName.trim())next.agencyName="Agency name is required.";if(!draft.timezone.trim())next.timezone="Timezone is required.";if(!draft.defaultThankYouMessage.trim())next.defaultThankYouMessage="Thank-you message is required.";if(draft.negativeFeedbackThreshold!==""&&(!Number.isFinite(Number(draft.negativeFeedbackThreshold))||Number(draft.negativeFeedbackThreshold)<1||Number(draft.negativeFeedbackThreshold)>5))next.negativeFeedbackThreshold="Choose a value from 1 to 5, or Not configured.";setFields(next);return Object.keys(next).length===0}
  async function submit(event:FormEvent){event.preventDefault();if(!saved||!draft||!validate())return;const original=draftOf(saved);const patch:UpdateAgencySettingsRequest={};if(draft.agencyName!==original.agencyName)patch.agencyName=draft.agencyName.trim();if(draft.timezone!==original.timezone)patch.timezone=draft.timezone.trim();if(draft.defaultThankYouMessage!==original.defaultThankYouMessage)patch.defaultThankYouMessage=draft.defaultThankYouMessage.trim();if(draft.negativeFeedbackThreshold!==original.negativeFeedbackThreshold)patch.negativeFeedbackThreshold=draft.negativeFeedbackThreshold===""?null:Number(draft.negativeFeedbackThreshold);if(!Object.keys(patch).length)return;setSaving(true);setError(null);setNotice("");try{const response=await apiRequest<{data:AgencySettings}>("/api/v1/admin/settings",{method:"PATCH",body:JSON.stringify(patch)});setSaved(response.data);setDraft(draftOf(response.data));setNotice("Settings saved.");invalidateCaches(["settings","passenger-context","analytics","feedback-lists","driver-performance","timezone"])}catch(cause){if(cause instanceof ApiError&&cause.code==="TIMEZONE_INVALID")setFields(current=>({...current,timezone:"Enter a valid IANA timezone, such as Asia/Kolkata."}));else setError({message:errorMessage(cause),requestId:cause instanceof ApiError?cause.requestId:undefined})}finally{setSaving(false)}}
  if(loading&&!draft)return <LoadingCards/>;
  if(error?.forbidden)return <div className="alert" role="alert"><strong>Admin access required.</strong><div>Your account cannot manage agency settings.</div></div>;
  if(!draft)return <>{error&&<ErrorAlert message={error.message} requestId={error.requestId}/>}<button className="button button-secondary" onClick={()=>void load(true)}>Try again</button></>;
  const set=(key:keyof Draft,value:string)=>{setDraft(current=>current?{...current,[key]:value}:current);setFields(current=>({...current,[key]:""}));setNotice("")};
  return <><div className="page-header"><div><p className="eyebrow">Agency configuration</p><h1>Settings</h1><p>Control agency identity, calendar grouping, passenger completion copy, and negative-feedback classification.</p></div><button className="button button-secondary" disabled={loading} onClick={()=>void load()}>{loading?"Refreshing…":"Reload"}</button></div>
    {error&&<ErrorAlert message={error.message} requestId={error.requestId}/>} {notice&&<div className="alert alert-info" role="status">{notice}</div>} {dirty&&<div className="alert alert-warning" role="status">You have unsaved changes.</div>}
    <form className="card card-pad settings-form" onSubmit={submit} noValidate>
      <Field id="agencyName" label="Agency name" value={draft.agencyName} error={fields.agencyName} onChange={value=>set("agencyName",value)}/>
      <Field id="timezone" label="IANA timezone" value={draft.timezone} error={fields.timezone} onChange={value=>set("timezone",value)} help="Controls calendar-month grouping and passenger-visible trip times. Example: Asia/Kolkata."/>
      <div className="field"><label htmlFor="defaultThankYouMessage">Default passenger thank-you message</label><textarea className="textarea" id="defaultThankYouMessage" maxLength={1000} value={draft.defaultThankYouMessage} onChange={event=>set("defaultThankYouMessage",event.target.value)} aria-invalid={!!fields.defaultThankYouMessage} aria-describedby={fields.defaultThankYouMessage?"defaultThankYouMessage-error":undefined}/>{fields.defaultThankYouMessage&&<small className="field-error" id="defaultThankYouMessage-error">{fields.defaultThankYouMessage}</small>}</div>
      <div className="field"><label htmlFor="negativeFeedbackThreshold">Negative-feedback threshold</label><select className="select" id="negativeFeedbackThreshold" value={draft.negativeFeedbackThreshold} onChange={event=>set("negativeFeedbackThreshold",event.target.value)} aria-describedby="threshold-help"><option value="">Not configured</option>{[1,2,3,4,5].map(value=><option key={value} value={value}>{value}</option>)}</select>{fields.negativeFeedbackThreshold&&<small className="field-error">{fields.negativeFeedbackThreshold}</small>}<small id="threshold-help">Feedback is negative when its scored-answer average is at or below this value. Clearing it disables classification and makes dashboard negative counts unavailable.</small></div>
      <div className="trip-actions"><button className="button" disabled={!dirty||saving}>{saving?"Saving…":"Save changed fields"}</button>{dirty&&<button type="button" className="button button-secondary" onClick={()=>setDraft(draftOf(saved!))}>Discard changes</button>}</div>
    </form></>;
}
function Field({id,label,value,error,help,onChange}:{id:string;label:string;value:string;error?:string;help?:string;onChange:(value:string)=>void}){const described=[error&&`${id}-error`,help&&`${id}-help`].filter(Boolean).join(" ")||undefined;return <div className="field"><label htmlFor={id}>{label}</label><input className="input" id={id} value={value} onChange={event=>onChange(event.target.value)} aria-invalid={!!error} aria-describedby={described}/>{error&&<small className="field-error" id={`${id}-error`}>{error}</small>}{help&&<small id={`${id}-help`}>{help}</small>}</div>}
