"use client";
/* eslint-disable @next/next/no-img-element -- object URLs are local previews and cannot use the image optimizer */

import { useCallback, useEffect, useMemo, useRef, useState, type ChangeEvent } from "react";
import { useRouter } from "next/navigation";
import { Brand } from "./brand";
import { ApiError, apiRequest, errorMessage, errorPresentation, isRetryable, type ApiErrorPresentation, type NormalizedFieldError } from "@/lib/api";
import type { AnswerValue, FeedbackAnswer, PassengerContext, PassengerFeedbackStart, PassengerQuestion, QuestionnairePurpose, SubmissionReceipt, SubmitFeedbackRequest } from "@/lib/contracts";
import { clearHandoff, getHandoff } from "@/lib/handoff";
import { enqueue } from "@/lib/offline-queue";
import { formatTripRange } from "@/lib/status";
import { passengerTokenFromSearch } from "@/lib/feedback-link";
import { formatPhotoSize, omitPhotoForOffline, PHOTO_ACCEPT, photoErrorMessage, uploadPassengerPhoto, validatePhotoFile, type CompletedPhotoResponse } from "@/lib/photo-upload";
import { ErrorAlert } from "./ui";
import { PhoneInput } from "./phone-input";
import { phoneError } from "@/lib/phone";
import type { E164Phone } from "@/lib/phone";

type Details={name:string;phone:string;email:string;bookingReference:string;consent:boolean};
type Stage="loading"|"details"|"questions"|"review"|"photo"|"submitting"|"complete"|"problem";
type ProblemKind="expired"|"unavailable"|"missing"|"generic";
type ScopedPassengerQuestion=PassengerQuestion&{sectionTitle:string;purpose:QuestionnairePurpose};
type PhotoState=
  |{kind:"empty"}
  |{kind:"selected";file:File;previewUrl:string}
  |{kind:"creating-intent";file:File;previewUrl:string}
  |{kind:"uploading";file:File;previewUrl:string;photoId:string}
  |{kind:"processing";file:File;previewUrl:string;photoId:string}
  |{kind:"ready";file:File;previewUrl:string;photoId:string}
  |{kind:"error";file?:File;previewUrl?:string;photoId?:string;message:string;retry:"upload"|"submit"};
const emptyDetails:Details={name:"",phone:"",email:"",bookingReference:"",consent:false};

function answerLabel(question:PassengerQuestion,value:AnswerValue|undefined){if(value===undefined)return "Not answered";if(Array.isArray(value))return value.map(key=>question.options.find(o=>o.valueKey===key)?.label||key).join(", ");if(question.questionType==="YES_NO")return value?"Yes":"No";if(typeof value==="string"&&question.options.length)return question.options.find(o=>o.valueKey===value)?.label||value;return String(value)}
function isAnswered(question:PassengerQuestion,value:AnswerValue|undefined){if(value===undefined||value===null)return false;if(typeof value==="string")return value.trim().length>0;if(Array.isArray(value))return value.length>0;return true}

function QuestionControl({question,value,onChange,error}:{question:PassengerQuestion;value:AnswerValue|undefined;onChange:(v:AnswerValue)=>void;error?:string}){
  const id=`question-${question.id}`;
  if(question.questionType==="STAR_RATING"){const min=question.scoreMin??1,max=question.scoreMax??5;return <fieldset className="question" aria-describedby={error?`${id}-error`:undefined}><legend><h2>{question.prompt} {question.isRequired&&<span aria-label="required">*</span>}</h2></legend><div className="rating">{Array.from({length:max-min+1},(_,index)=>min+index).map(score=><button key={score} type="button" aria-pressed={value===score} data-highlighted={typeof value==="number"&&score<=value} aria-label={`${score} out of ${max}`} onClick={()=>onChange(score)}>★<span className="sr-only">{score}</span></button>)}</div>{error&&<div className="alert" id={`${id}-error`}>{error}</div>}</fieldset>}
  if(question.questionType==="TEXT")return <div className="question"><label htmlFor={id}><h2>{question.prompt} {question.isRequired&&<span aria-label="required">*</span>}</h2></label><textarea className="textarea" id={id} value={typeof value==="string"?value:""} onChange={e=>onChange(e.target.value)} aria-invalid={!!error} aria-describedby={error?`${id}-error`:undefined}/>{error&&<div className="alert" id={`${id}-error`}>{error}</div>}</div>;
  if(question.questionType==="YES_NO")return <fieldset className="question"><legend><h2>{question.prompt} {question.isRequired&&<span aria-label="required">*</span>}</h2></legend><div className="choice-grid">{[{label:"Yes",value:true},{label:"No",value:false}].map(option=><label className="choice" key={option.label}><input type="radio" name={id} checked={value===option.value} onChange={()=>onChange(option.value)}/><span>{option.label}</span></label>)}</div>{error&&<div className="alert">{error}</div>}</fieldset>;
  const multiple=question.questionType==="MULTIPLE_CHOICE";return <fieldset className="question"><legend><h2>{question.prompt} {question.isRequired&&<span aria-label="required">*</span>}</h2></legend><div className="choice-grid">{question.options.map(option=>{const checked=multiple?Array.isArray(value)&&value.includes(option.valueKey):value===option.valueKey;return <label className="choice" key={option.valueKey}><input type={multiple?"checkbox":"radio"} name={id} checked={checked} onChange={()=>{if(multiple){const current=Array.isArray(value)?value:[];onChange(checked?current.filter(k=>k!==option.valueKey):[...current,option.valueKey])}else onChange(option.valueKey)}}/><span>{question.questionType==="EMOJI_RATING"&&<span aria-hidden="true">{["○","◔","◑","◕","●"][question.options.indexOf(option)]||"●"} </span>}{option.label}</span></label>})}</div>{error&&<div className="alert">{error}</div>}</fieldset>;
}

export function PassengerFlow(){
  const router=useRouter();
  const [stage,setStage]=useState<Stage>("loading");
  const [context,setContext]=useState<PassengerContext|null>(null);
  const [completion,setCompletion]=useState<PassengerContext["completion"]|null>(null);
  const [details,setDetails]=useState<Details>(emptyDetails);
  const [answers,setAnswers]=useState<Record<string,AnswerValue>>({});
  const [questionIndex,setQuestionIndex]=useState(0);
  const [error,setError]=useState<ApiErrorPresentation|null>(null);
  const [problemKind,setProblemKind]=useState<ProblemKind>("generic");
  const [fieldErrors,setFieldErrors]=useState<Record<string,string>>({});
  const [backendSummary,setBackendSummary]=useState<NormalizedFieldError[]>([]);
  void backendSummary; // Field messages are surfaced inline in this staged form.
  const [startingQuestions,setStartingQuestions]=useState(false);
  const [feedbackStarted,setFeedbackStarted]=useState(false);
  const [photo,setPhoto]=useState<PhotoState>({kind:"empty"});
  const photoGeneration=useRef(0);
  const photoAbort=useRef<AbortController|null>(null);
  const libraryInput=useRef<HTMLInputElement|null>(null);
  const submissionId=useRef<string|null>(null);
  const submissionInFlight=useRef(false);
  const [access]=useState(()=>{if(typeof window==="undefined")return null;const linkToken=passengerTokenFromSearch(window.location.search);if(linkToken)return{token:linkToken,sharedLink:true};const handoff=getHandoff();return handoff?{token:handoff.token,sharedLink:false}:null});
  const token=access?.token??null,sharedLink=access?.sharedLink??false;
  const questions=useMemo<ScopedPassengerQuestion[]>(()=>context?.questionnaire.sections.flatMap((section)=>section.questions.map((question)=>({...question,sectionTitle:section.title,purpose:section.purpose})))??[],[context]);
  const totalSteps=questions.length+3;
  const currentStep=stage==="details"?1:stage==="questions"?questionIndex+2:stage==="review"?Math.max(2,totalSteps-1):totalSteps;
  const previewUrl="previewUrl" in photo?photo.previewUrl:undefined;

  const loadContext=useCallback(async()=>{if(!token){setProblemKind("missing");setError({message:"This feedback link is missing its access token. Ask the driver for the complete link."});setStage("problem");return}setStage("loading");setError(null);try{const response=await apiRequest<{data:PassengerContext}>("/api/v1/passenger/feedback/context",{passengerToken:token});setContext(response.data);setCompletion(response.data.completion);setDetails(value=>({...value,bookingReference:response.data.engagement.bookingReference}));setProblemKind("generic");setStage("details")}catch(cause){const kind:ProblemKind=cause instanceof ApiError&&cause.code==="FEEDBACK_HANDOFF_INVALID"?"expired":cause instanceof ApiError&&(cause.status===404||cause.code==="FEEDBACK_HANDOFF_UNAVAILABLE")?"unavailable":"generic";setProblemKind(kind);setError({...errorPresentation(cause),message:cause instanceof ApiError&&cause.status===404?"This engagement is unavailable.":errorMessage(cause)});setStage("problem")}},[token]);
  useEffect(()=>{queueMicrotask(()=>void loadContext())},[loadContext]);
  useEffect(()=>{const warn=(event:BeforeUnloadEvent)=>{if(["details","questions","review","photo","submitting"].includes(stage)){event.preventDefault();event.returnValue=""}};window.addEventListener("beforeunload",warn);return()=>window.removeEventListener("beforeunload",warn)},[stage]);
  useEffect(()=>()=>{if(previewUrl)URL.revokeObjectURL(previewUrl)},[previewUrl]);
  useEffect(()=>()=>photoAbort.current?.abort(),[]);

  const progress=Math.min(100,Math.round(currentStep/Math.max(totalSteps,1)*100));
  function validateDetails(){const errors:Record<string,string>={};if(!details.name.trim())errors.name="Enter your name.";const invalidPhone=phoneError(details.phone);if(invalidPhone)errors.phone=invalidPhone;if(!/^\S+@\S+\.\S+$/.test(details.email))errors.email="Enter a valid email address.";if(!details.bookingReference.trim())errors.bookingReference="Enter the booking reference.";if(!details.consent)errors.consent="Consent is required before feedback can be collected.";setFieldErrors(errors);return Object.keys(errors).length===0}
  async function nextFromDetails(){if(!validateDetails()||!token)return;setFieldErrors({});setBackendSummary([]);setError(null);if(feedbackStarted){setStage("questions");return}setStartingQuestions(true);try{await apiRequest<{data:PassengerFeedbackStart}>("/api/v1/passenger/feedback/start",{method:"POST",passengerToken:token});setFeedbackStarted(true);setStage("questions")}catch(cause){setError({...errorPresentation(cause),message:cause instanceof ApiError&&cause.status===404?"This engagement is unavailable.":errorMessage(cause)});if(cause instanceof ApiError&&cause.code==="FEEDBACK_HANDOFF_INVALID"){setProblemKind("expired");setStage("problem")}else if(cause instanceof ApiError&&(cause.status===404||cause.code==="FEEDBACK_HANDOFF_UNAVAILABLE"||cause.code==="ENGAGEMENT_FEEDBACK_ALREADY_SUBMITTED")){setProblemKind("unavailable");setStage("problem")}}finally{setStartingQuestions(false)}}
  function nextQuestion(){const q=questions[questionIndex];if(q.isRequired&&!isAnswered(q,answers[q.id])){setFieldErrors({[q.id]:"Choose or enter an answer before continuing."});return}setFieldErrors({});if(questionIndex<questions.length-1)setQuestionIndex(i=>i+1);else setStage("review")}
  function previousQuestion(){setFieldErrors({});if(questionIndex>0)setQuestionIndex(i=>i-1);else setStage("details")}
  const builtAnswers=useMemo<FeedbackAnswer[]>(()=>questions.filter(q=>isAnswered(q,answers[q.id])).map(q=>({questionId:q.id,value:answers[q.id]})),[answers,questions]);

  function terminalPhotoError(cause:unknown){if(cause instanceof ApiError&&cause.code==="FEEDBACK_HANDOFF_INVALID"){setProblemKind("expired");setError(errorPresentation(cause));setStage("problem");return true}if(cause instanceof ApiError&&(cause.status===404||cause.code==="FEEDBACK_HANDOFF_UNAVAILABLE")){setProblemKind("unavailable");setError(errorPresentation(cause));setStage("problem");return true}return false}
  function cancelPhotoOperation(){photoGeneration.current+=1;photoAbort.current?.abort();photoAbort.current=null}
  function choosePhoto(event:ChangeEvent<HTMLInputElement>){const file=event.target.files?.[0];event.target.value="";if(!file)return;cancelPhotoOperation();const validation=validatePhotoFile(file);if(validation){setPhoto({kind:"error",file,message:validation.message,retry:"upload"});return}setPhoto({kind:"selected",file,previewUrl:URL.createObjectURL(file)})}
  function removePhoto(){cancelPhotoOperation();setPhoto({kind:"empty"})}
  async function uploadPhoto(){if(!token)return;const file="file" in photo?photo.file:undefined,existingPreview="previewUrl" in photo?photo.previewUrl:undefined;if(!file)return;if(!navigator.onLine){setPhoto({kind:"error",file,previewUrl:existingPreview,message:"Photo upload needs an internet connection. Try again when connected, or continue without the photo.",retry:"upload"});return}cancelPhotoOperation();const generation=photoGeneration.current;const controller=new AbortController();photoAbort.current=controller;const preview=existingPreview??URL.createObjectURL(file);setPhoto({kind:"creating-intent",file,previewUrl:preview});try{const completed=await uploadPassengerPhoto(file,token,{signal:controller.signal,onIntent:intent=>{if(generation===photoGeneration.current)setPhoto({kind:"uploading",file,previewUrl:preview,photoId:intent.id})},onUploaded:photoId=>{if(generation===photoGeneration.current)setPhoto({kind:"processing",file,previewUrl:preview,photoId})}});if(generation!==photoGeneration.current)return;setPhoto({kind:"ready",file,previewUrl:preview,photoId:completed.data.id})}catch(cause){if(generation!==photoGeneration.current||controller.signal.aborted)return;if(terminalPhotoError(cause))return;setPhoto({kind:"error",file,previewUrl:preview,message:photoErrorMessage(cause),retry:"upload"})}finally{if(generation===photoGeneration.current)photoAbort.current=null}}

  function makeEnvelope(photoId?:string):SubmitFeedbackRequest{if(!context)throw new Error("Feedback context is unavailable.");submissionId.current??=crypto.randomUUID();const now=new Date().toISOString();return{clientSubmissionId:submissionId.current,questionnaireSnapshot:context.questionnaire,respondent:{name:details.name.trim(),phone:details.phone as E164Phone,email:details.email.trim(),bookingReference:details.bookingReference.trim(),consentAccepted:true,consentedAt:now},answers:builtAnswers,submittedAt:now,submissionMode:"ONLINE",...(photoId?{photoId}:{})}}
  async function completeOnce(photoId:string){if(!token)return;await apiRequest<CompletedPhotoResponse>(`/api/v1/passenger/feedback/photo-uploads/${encodeURIComponent(photoId)}/complete`,{method:"POST",passengerToken:token,timeoutMs:30000})}
  async function sendOnline(envelope:SubmitFeedbackRequest){if(!token)return;try{await apiRequest<{data:SubmissionReceipt}>("/api/v1/passenger/feedback/submissions",{method:"POST",passengerToken:token,body:JSON.stringify(envelope),timeoutMs:15000})}catch(cause){if(cause instanceof ApiError&&cause.code==="PHOTO_NOT_READY"&&envelope.photoId){await completeOnce(envelope.photoId);await apiRequest<{data:SubmissionReceipt}>("/api/v1/passenger/feedback/submissions",{method:"POST",passengerToken:token,body:JSON.stringify(envelope),timeoutMs:15000});return}throw cause}}
  function showSubmissionFieldErrors(cause:ApiError,envelope:SubmitFeedbackRequest){if(!cause.fieldErrors.length)return false;const next:Record<string,string>={};let firstDetail:string|undefined;let firstQuestion=-1;for(const issue of cause.fieldErrors){const detail=issue.field.match(/^respondent\.(name|phone|email|bookingReference|consentAccepted)$/)?.[1];if(detail){const key=detail==="consentAccepted"?"consent":detail;next[key]=issue.message;firstDetail??=key;continue}const answerIndex=Number(issue.field.match(/^answers\.(\d+)(?:\.|$)/)?.[1]);if(Number.isInteger(answerIndex)&&envelope.answers[answerIndex]){const questionId=envelope.answers[answerIndex].questionId;next[questionId]=issue.message;const index=questions.findIndex(question=>question.id===questionId);if(firstQuestion<0)firstQuestion=index}}setFieldErrors(next);setBackendSummary(cause.fieldErrors);if(firstDetail){setStage("details");queueMicrotask(()=>document.getElementById(firstDetail==="phone"?"respondentPhone-national":firstDetail)?.focus())}else if(firstQuestion>=0){setQuestionIndex(firstQuestion);setStage("questions");queueMicrotask(()=>document.getElementById(`question-${questions[firstQuestion].id}`)?.focus())}return true}
  async function submit(photoId?:string){if(!context||!token||submissionInFlight.current)return;const requiredMissing=questions.some(q=>q.isRequired&&!isAnswered(q,answers[q.id]));if(requiredMissing){setStage("questions");setQuestionIndex(Math.max(0,questions.findIndex(q=>q.isRequired&&!isAnswered(q,answers[q.id]))));return}submissionInFlight.current=true;cancelPhotoOperation();setStage("submitting");setError(null);setBackendSummary([]);const envelope=makeEnvelope(photoId);try{if(!navigator.onLine){if(sharedLink)throw new ApiError(0,"NETWORK_UNAVAILABLE","The service could not be reached.",undefined,undefined,"transport");await enqueue(token,omitPhotoForOffline(envelope))}else{try{await sendOnline(envelope)}catch(cause){if(!sharedLink&&isRetryable(cause))await enqueue(token,omitPhotoForOffline(envelope));else throw cause}}setDetails(emptyDetails);setAnswers({});setContext(null);setPhoto({kind:"empty"});submissionId.current=null;clearHandoff();const basePath=process.env.NEXT_PUBLIC_BASE_PATH??"";history.replaceState(null,"",`${basePath}/feedback/hand-back/`);setStage("complete")}catch(cause){if(cause instanceof ApiError&&cause.code==="ENGAGEMENT_FEEDBACK_ALREADY_SUBMITTED"){setProblemKind("unavailable");setError(errorPresentation(cause));setStage("problem");return}if(terminalPhotoError(cause))return;if(cause instanceof ApiError&&showSubmissionFieldErrors(cause,envelope)){setError(errorPresentation(cause));return}if(photoId){setPhoto(current=>({kind:"error",...(current.kind!=="empty"&&"previewUrl" in current?{previewUrl:current.previewUrl}:{}),photoId,message:photoErrorMessage(cause),retry:"submit"}));setStage("photo");return}setError({...errorPresentation(cause),message:cause instanceof ApiError&&cause.status===404?"This engagement is unavailable.":errorMessage(cause)});setStage("review")}finally{submissionInFlight.current=false}}
  function retryPhoto(){if(photo.kind!=="error")return;if(photo.retry==="submit"&&photo.photoId)void submit(photo.photoId);else void uploadPhoto()}
  function skipPhoto(){removePhoto();void submit()}

  if(stage==="loading")return <main className="passenger-page"><div className="passenger-shell"><header className="passenger-head"><Brand compact/><span className="secure-note">Preparing private feedback</span></header><div className="skeleton"/><div className="skeleton" style={{marginTop:"1rem"}}/></div></main>;
  if(stage==="complete")return <main className="passenger-page"><div className="passenger-shell"><header className="passenger-head"><Brand compact/></header><section className="completion"><div className="completion-mark" aria-hidden="true">✓</div><p className="eyebrow">{completion?.agencyName}</p><h1>Thank you for sharing your journey.</h1><p>{completion?.thankYouMessage}</p>{!sharedLink&&<><div className="handback">Please return this device to your driver</div><button className="button button-secondary" onClick={()=>router.replace("/driver")}>Driver unlock</button></>}</section></div></main>;
  if(stage==="problem")return <main className="passenger-page"><div className="passenger-shell"><header className="passenger-head"><Brand compact/></header><section className="completion"><div className="completion-mark" aria-hidden="true">!</div><h1>{problemKind==="expired"?"This feedback link has expired.":problemKind==="unavailable"?"This engagement is unavailable.":"This feedback link is not available."}</h1>{error&&<ErrorAlert message={error.message} requestId={error.requestId}/>}<div className="passenger-problem-actions">{problemKind!=="missing"&&<button className="button" onClick={()=>void loadContext()}>Try again</button>}<button className="button button-secondary" onClick={()=>router.replace("/")}>Close feedback</button></div></section></div></main>;
  const progressLabel=stage==="details"?"Your details":stage==="questions"?"Journey questions":stage==="review"?"Review":"Optional photo";
  return <main className="passenger-page"><div className="passenger-shell"><header className="passenger-head"><Brand compact/><span className="secure-note">Passenger-safe feedback</span></header><div className="progress-wrap" aria-label={`Step ${currentStep} of ${totalSteps}`}><div className="progress-label"><span>Step {currentStep} of {totalSteps}</span><span>{progressLabel}</span></div><div className="progress"><span style={{width:`${progress}%`}}/></div></div>
    {stage==="details"&&context&&<><p className="eyebrow">Welcome to {context.completion.agencyName}</p><h1 className="passenger-title">Your journey matters to us.</h1><p className="passenger-copy">Review the trips covered by this driver engagement, then tell us a little about yourself.</p>{error&&<ErrorAlert message={error.message} requestId={error.requestId}/>}<section className="card trip-summary"><div className="trip-summary-grid"><span><small>Booking</small>{context.engagement.bookingReference}</span><span><small>Driver</small>{context.engagement.driver.displayName}</span><span><small>Engagement</small>#{context.engagement.sequenceNumber}</span><span><small>Trips</small>{context.engagement.trips.length}</span></div><ol className="history-list">{[...context.engagement.trips].sort((a,b)=>a.scheduledAt.localeCompare(b.scheduledAt)).map(trip=><li key={trip.id}><strong>{trip.pickupLocation} → {trip.destination}</strong><small>{formatTripRange(trip.scheduledAt,trip.scheduledEndAt,context.completion.timezone)} · {trip.vehicle.displayName} · {trip.vehicle.registrationNumber}</small></li>)}</ol></section><section className="card passenger-card"><h2 className="section-title">About you</h2>{([['name','Name','text'],['email','Email address','email'],['bookingReference','Booking reference','text']] as const).map(([key,label,type])=><div className="field" key={key}><label htmlFor={key}>{label}</label><input className="input" id={key} type={type} value={String(details[key])} onChange={e=>setDetails({...details,[key]:e.target.value})} aria-invalid={!!fieldErrors[key]} aria-describedby={fieldErrors[key]?`${key}-error`:undefined}/>{fieldErrors[key]&&<small id={`${key}-error`} style={{color:"var(--danger)"}}>{fieldErrors[key]}</small>}</div>)}<PhoneInput name="respondentPhone" label="Phone number" value={details.phone} error={fieldErrors.phone} onValueChange={(phone)=>setDetails({...details,phone})}/><h2 className="section-title">Privacy and consent</h2><div className="consent-box">{context.consent.content}</div><label className="check-row"><input type="checkbox" checked={details.consent} onChange={e=>setDetails({...details,consent:e.target.checked})}/><span>I have read the notice and consent to the collection and use of my feedback information.</span></label>{fieldErrors.consent&&<div className="alert">{fieldErrors.consent}</div>}</section><div className="passenger-actions"><span/><button className="button" disabled={startingQuestions} onClick={()=>void nextFromDetails()}>{startingQuestions?"Opening questions…":"Continue to questions →"}</button></div></>}
    {stage==="questions"&&questions[questionIndex]&&<><p className="eyebrow">{questions[questionIndex].sectionTitle}</p><section className="card passenger-card"><QuestionControl question={questions[questionIndex]} value={answers[questions[questionIndex].id]} onChange={value=>setAnswers({...answers,[questions[questionIndex].id]:value})} error={fieldErrors[questions[questionIndex].id]}/></section><div className="passenger-actions"><button className="button button-secondary" onClick={previousQuestion}>← Previous</button><button className="button" onClick={nextQuestion}>{questionIndex===questions.length-1?"Review feedback →":"Next question →"}</button></div></>}
    {stage==="review"&&context&&<><p className="eyebrow">Almost there</p><h1 className="passenger-title">Review your feedback.</h1><p className="passenger-copy">Submitted feedback cannot be edited. You can go back now if anything needs changing.</p>{error&&<ErrorAlert message={error.message} requestId={error.requestId}/>}<div className="review-sections">{context.questionnaire.sections.map((section)=><section className="card passenger-card" key={section.purpose}><h2 className="section-title">{section.title}</h2><div className="review-list">{section.questions.map(q=><div className="review-row" key={q.id}><small>{q.prompt}</small><strong>{answerLabel(q,answers[q.id])}</strong></div>)}</div></section>)}</div><div className="passenger-actions"><button className="button button-secondary" onClick={()=>{setQuestionIndex(Math.max(0,questions.length-1));setStage("questions")}}>← Edit answers</button><button className="button" onClick={()=>setStage("photo")}>Continue →</button></div></>}
    {stage==="photo"&&<><p className="eyebrow">Optional</p><h1 className="passenger-title">Add a photo with your driver.</h1><p className="passenger-copy">You may add one photo or skip this step. Your photo will be stored securely and visible only to authorised Eastern Risen administrators.</p><section className="card passenger-card photo-card">
      <div className="photo-input-actions"><label className="button" htmlFor="camera-photo">Take photo<input className="sr-only" id="camera-photo" type="file" accept={PHOTO_ACCEPT} capture="environment" onChange={choosePhoto}/></label><label className="button button-secondary" htmlFor="library-photo">Choose from library<input ref={libraryInput} className="sr-only" id="library-photo" type="file" accept={PHOTO_ACCEPT} onChange={choosePhoto}/></label></div>
      {previewUrl&&<figure className="photo-preview"><img src={previewUrl} alt="Preview of the selected trip photo"/><figcaption>{"file" in photo&&photo.file?<><strong>{photo.file.name||"Selected photo"}</strong><span>{formatPhotoSize(photo.file.size)}</span></>:<span>Selected photo</span>}</figcaption></figure>}
      {photo.kind==="empty"&&<p className="photo-help">JPEG, PNG, or WebP only. Maximum preliminary size: 10 MB.</p>}
      {photo.kind==="selected"&&<div className="photo-status" role="status">Photo selected. Upload it when you are ready.</div>}
      {photo.kind==="creating-intent"&&<div className="photo-status" role="status" aria-live="polite">Preparing a secure upload…</div>}
      {photo.kind==="uploading"&&<div className="photo-status" role="status" aria-live="polite">Uploading your photo…</div>}
      {photo.kind==="processing"&&<div className="photo-status" role="status" aria-live="polite"><strong>Processing your photo…</strong><span>Eastern Risen is checking the image and removing location and camera metadata. This may take a few seconds.</span></div>}
      {photo.kind==="ready"&&<div className="photo-status photo-ready" role="status">✓ Photo is ready to attach.</div>}
      {photo.kind==="error"&&<div className="alert photo-error" role="alert"><strong>Photo not added</strong><div>{photo.message}</div></div>}
      <div className="photo-controls">{photo.kind!=="empty"&&<><button type="button" className="button button-secondary" disabled={["creating-intent","uploading","processing"].includes(photo.kind)} onClick={()=>libraryInput.current?.click()}>Replace</button><button type="button" className="button button-secondary" onClick={removePhoto}>Remove</button></>}{photo.kind==="selected"&&<button type="button" className="button" onClick={()=>void uploadPhoto()}>Upload photo</button>}{photo.kind==="ready"&&<button type="button" className="button" onClick={()=>void submit(photo.photoId)}>Submit feedback with photo</button>}{photo.kind==="error"&&<button type="button" className="button" onClick={retryPhoto}>Try again</button>}</div>
    </section><div className="passenger-actions"><button className="button button-secondary" onClick={()=>setStage("review")}>← Back to review</button><button className="button button-plain" onClick={skipPhoto}>Continue without photo</button></div></>}
    {stage==="submitting"&&<section className="completion"><div className="completion-mark" aria-hidden="true">↗</div><h1>Saving your feedback…</h1><p>Please keep this screen open for a moment.</p></section>}
  </div></main>;
}
