"use client";

import { useCallback,useEffect,useMemo,useState } from "react";
import { useRouter } from "next/navigation";
import { Brand } from "./brand";
import { ApiError, apiRequest, errorMessage, isRetryable } from "@/lib/api";
import type { AnswerValue, FeedbackAnswer, PassengerContext, PassengerFeedbackStart, PassengerQuestion, SubmissionReceipt, SubmitFeedbackRequest } from "@/lib/contracts";
import { clearHandoff,getHandoff } from "@/lib/handoff";
import { enqueue } from "@/lib/offline-queue";
import { formatTripRange } from "@/lib/status";
import { passengerTokenFromSearch } from "@/lib/feedback-link";
import { ErrorAlert } from "./ui";

type Details={name:string;phone:string;email:string;bookingReference:string;consent:boolean};
type Stage="loading"|"details"|"questions"|"review"|"submitting"|"complete"|"problem";
type ProblemKind="expired"|"unavailable"|"missing"|"generic";
const emptyDetails:Details={name:"",phone:"",email:"",bookingReference:"",consent:false};

function answerLabel(question:PassengerQuestion,value:AnswerValue|undefined){if(value===undefined)return "Not answered";if(Array.isArray(value))return value.map(key=>question.options.find(o=>o.valueKey===key)?.label||key).join(", ");if(question.questionType==="YES_NO")return value?"Yes":"No";if(typeof value==="string"&&question.options.length)return question.options.find(o=>o.valueKey===value)?.label||value;return String(value)}
function isAnswered(question:PassengerQuestion,value:AnswerValue|undefined){if(value===undefined||value===null)return false;if(typeof value==="string")return value.trim().length>0;if(Array.isArray(value))return value.length>0;return true}

function QuestionControl({question,value,onChange,error}:{question:PassengerQuestion;value:AnswerValue|undefined;onChange:(v:AnswerValue)=>void;error?:string}){
  const id=`question-${question.id}`;
  if(question.questionType==="STAR_RATING"){const min=question.scoreMin??1,max=question.scoreMax??5;return <fieldset className="question" aria-describedby={error?`${id}-error`:undefined}><legend><h2>{question.prompt} {question.isRequired&&<span aria-label="required">*</span>}</h2></legend><div className="rating">{Array.from({length:max-min+1},(_,index)=>min+index).map(score=><button key={score} type="button" aria-pressed={value===score} data-highlighted={typeof value==="number"&&score<=value} aria-label={`${score} out of ${max}`} onClick={()=>onChange(score)}>★<span className="sr-only">{score}</span></button>)}</div>{error&&<div className="alert" id={`${id}-error`}>{error}</div>}</fieldset>}
  if(question.questionType==="TEXT")return <div className="question"><label htmlFor={id}><h2>{question.prompt} {question.isRequired&&<span aria-label="required">*</span>}</h2></label><textarea className="textarea" id={id} value={typeof value==="string"?value:""} onChange={e=>onChange(e.target.value)} aria-invalid={!!error} aria-describedby={error?`${id}-error`:undefined}/>{error&&<div className="alert" id={`${id}-error`}>{error}</div>}</div>;
  if(question.questionType==="YES_NO"){return <fieldset className="question"><legend><h2>{question.prompt} {question.isRequired&&<span aria-label="required">*</span>}</h2></legend><div className="choice-grid">{[{label:"Yes",value:true},{label:"No",value:false}].map(option=><label className="choice" key={option.label}><input type="radio" name={id} checked={value===option.value} onChange={()=>onChange(option.value)}/><span>{option.label}</span></label>)}</div>{error&&<div className="alert">{error}</div>}</fieldset>}
  const multiple=question.questionType==="MULTIPLE_CHOICE";return <fieldset className="question"><legend><h2>{question.prompt} {question.isRequired&&<span aria-label="required">*</span>}</h2></legend><div className="choice-grid">{question.options.map(option=>{const checked=multiple?Array.isArray(value)&&value.includes(option.valueKey):value===option.valueKey;return <label className="choice" key={option.valueKey}><input type={multiple?"checkbox":"radio"} name={id} checked={checked} onChange={()=>{if(multiple){const current=Array.isArray(value)?value:[];onChange(checked?current.filter(k=>k!==option.valueKey):[...current,option.valueKey])}else onChange(option.valueKey)}}/><span>{question.questionType==="EMOJI_RATING"&&<span aria-hidden="true">{["○","◔","◑","◕","●"][question.options.indexOf(option)]||"●"} </span>}{option.label}</span></label>})}</div>{error&&<div className="alert">{error}</div>}</fieldset>;
}

export function PassengerFlow(){const router=useRouter();const [stage,setStage]=useState<Stage>("loading");const [context,setContext]=useState<PassengerContext|null>(null);const [completion,setCompletion]=useState<PassengerContext["completion"]|null>(null);const [details,setDetails]=useState<Details>(emptyDetails);const [answers,setAnswers]=useState<Record<string,AnswerValue>>({});const [questionIndex,setQuestionIndex]=useState(0);const [error,setError]=useState<{message:string;requestId?:string}|null>(null);const [problemKind,setProblemKind]=useState<ProblemKind>("generic");const [fieldErrors,setFieldErrors]=useState<Record<string,string>>({});const [startingQuestions,setStartingQuestions]=useState(false);const [feedbackStarted,setFeedbackStarted]=useState(false);const [access]=useState(()=>{if(typeof window==="undefined")return null;const linkToken=passengerTokenFromSearch(window.location.search);if(linkToken)return{token:linkToken,sharedLink:true};const handoff=getHandoff();return handoff?{token:handoff.token,sharedLink:false}:null});const token=access?.token??null;const sharedLink=access?.sharedLink??false;
  const questions=useMemo(()=>context?.questionnaire.questions??[],[context]);const totalSteps=questions.length+2;const currentStep=stage==="details"?1:stage==="questions"?questionIndex+2:totalSteps;
  const loadContext=useCallback(async()=>{if(!token){setProblemKind("missing");setError({message:"This feedback link is missing its access token. Ask the driver for the complete link."});setStage("problem");return}setStage("loading");setError(null);try{const response=await apiRequest<{data:PassengerContext}>("/api/v1/passenger/feedback/context",{passengerToken:token});setContext(response.data);setCompletion(response.data.completion);setDetails(value=>({...value,bookingReference:response.data.trip.bookingReference}));setProblemKind("generic");setStage("details")}catch(cause){const kind:ProblemKind=cause instanceof ApiError&&cause.code==="FEEDBACK_HANDOFF_INVALID"?"expired":cause instanceof ApiError&&(cause.status===404||cause.code==="FEEDBACK_HANDOFF_UNAVAILABLE")?"unavailable":"generic";setProblemKind(kind);setError({message:cause instanceof ApiError&&cause.status===404?"This trip is unavailable.":errorMessage(cause),requestId:cause instanceof ApiError?cause.requestId:undefined});setStage("problem")}},[token]);
  useEffect(()=>{queueMicrotask(()=>void loadContext())},[loadContext]);
  useEffect(()=>{const warn=(event:BeforeUnloadEvent)=>{if(["details","questions","review","submitting"].includes(stage)){event.preventDefault();event.returnValue=""}};window.addEventListener("beforeunload",warn);return()=>window.removeEventListener("beforeunload",warn)},[stage]);
  const progress=Math.min(100,Math.round(currentStep/Math.max(totalSteps,1)*100));
  function validateDetails(){const errors:Record<string,string>={};if(!details.name.trim())errors.name="Enter your name.";if(!details.phone.trim())errors.phone="Enter your phone number.";if(!/^\S+@\S+\.\S+$/.test(details.email))errors.email="Enter a valid email address.";if(!details.bookingReference.trim())errors.bookingReference="Enter the booking reference.";if(!details.consent)errors.consent="Consent is required before feedback can be collected.";setFieldErrors(errors);return Object.keys(errors).length===0}
  async function nextFromDetails(){if(!validateDetails()||!token)return;setFieldErrors({});setError(null);if(feedbackStarted){setStage("questions");return}setStartingQuestions(true);try{await apiRequest<{data:PassengerFeedbackStart}>("/api/v1/passenger/feedback/start",{method:"POST",passengerToken:token});setFeedbackStarted(true);setStage("questions")}catch(cause){const nextError={message:cause instanceof ApiError&&cause.status===404?"This trip is unavailable.":errorMessage(cause),requestId:cause instanceof ApiError?cause.requestId:undefined};setError(nextError);if(cause instanceof ApiError&&cause.code==="FEEDBACK_HANDOFF_INVALID"){setProblemKind("expired");setStage("problem")}else if(cause instanceof ApiError&&(cause.status===404||cause.code==="FEEDBACK_HANDOFF_UNAVAILABLE")){setProblemKind("unavailable");setStage("problem")}}finally{setStartingQuestions(false)}}
  function nextQuestion(){const q=questions[questionIndex];if(q.isRequired&&!isAnswered(q,answers[q.id])){setFieldErrors({[q.id]:"Choose or enter an answer before continuing."});return}setFieldErrors({});if(questionIndex<questions.length-1)setQuestionIndex(i=>i+1);else setStage("review")}
  function previousQuestion(){setFieldErrors({});if(questionIndex>0)setQuestionIndex(i=>i-1);else setStage("details")}
  const builtAnswers=useMemo<FeedbackAnswer[]>(()=>questions.filter(q=>isAnswered(q,answers[q.id])).map(q=>({questionId:q.id,value:answers[q.id]})),[answers,questions]);
  async function submit(){if(!context||!token)return;const requiredMissing=questions.some(q=>q.isRequired&&!isAnswered(q,answers[q.id]));if(requiredMissing){setStage("questions");setQuestionIndex(Math.max(0,questions.findIndex(q=>q.isRequired&&!isAnswered(q,answers[q.id]))));return}setStage("submitting");setError(null);const now=new Date().toISOString();const envelope:SubmitFeedbackRequest={clientSubmissionId:crypto.randomUUID(),questionnaireVersionId:context.questionnaire.questionnaireVersionId,questionnaireSnapshot:context.questionnaire,respondent:{name:details.name.trim(),phone:details.phone.trim(),email:details.email.trim(),bookingReference:details.bookingReference.trim(),consentAccepted:true,consentedAt:now},answers:builtAnswers,submittedAt:now,submissionMode:"ONLINE"};
    try{if(!navigator.onLine){if(sharedLink)throw new ApiError(0,"NETWORK_UNAVAILABLE","The service could not be reached.",undefined,undefined,"transport");await enqueue(token,envelope)}else{try{await apiRequest<{data:SubmissionReceipt}>("/api/v1/passenger/feedback/submissions",{method:"POST",passengerToken:token,body:JSON.stringify(envelope),timeoutMs:15000})}catch(cause){if(!sharedLink&&isRetryable(cause))await enqueue(token,envelope);else throw cause}}setDetails(emptyDetails);setAnswers({});setContext(null);clearHandoff();const basePath=process.env.NEXT_PUBLIC_BASE_PATH??"";history.replaceState(null,"",`${basePath}/feedback/hand-back/`);setStage("complete")}catch(cause){setError({message:cause instanceof ApiError&&cause.status===404?"This trip is unavailable.":errorMessage(cause),requestId:cause instanceof ApiError?cause.requestId:undefined});if(cause instanceof ApiError&&cause.code==="FEEDBACK_HANDOFF_INVALID"){setProblemKind("expired");setStage("problem")}else if(cause instanceof ApiError&&(cause.status===404||cause.code==="FEEDBACK_HANDOFF_UNAVAILABLE")){setProblemKind("unavailable");setStage("problem")}else setStage("review")}}
  if(stage==="loading")return <main className="passenger-page"><div className="passenger-shell"><header className="passenger-head"><Brand compact/><span className="secure-note">Preparing private feedback</span></header><div className="skeleton"/><div className="skeleton" style={{marginTop:"1rem"}}/></div></main>;
  if(stage==="complete")return <main className="passenger-page"><div className="passenger-shell"><header className="passenger-head"><Brand compact/></header><section className="completion"><div className="completion-mark" aria-hidden="true">✓</div><p className="eyebrow">{completion?.agencyName}</p><h1>Thank you for sharing your journey.</h1><p>{completion?.thankYouMessage}</p>{!sharedLink&&<><div className="handback">Please return this device to your driver</div><button className="button button-secondary" onClick={()=>router.replace("/driver")}>Driver unlock</button></>}</section></div></main>;
  if(stage==="problem")return <main className="passenger-page"><div className="passenger-shell"><header className="passenger-head"><Brand compact/></header><section className="completion"><div className="completion-mark" aria-hidden="true">!</div><h1>{problemKind==="expired"?"This feedback link has expired.":problemKind==="unavailable"?"This trip is unavailable.":"This feedback link is not available."}</h1>{error&&<ErrorAlert message={error.message} requestId={error.requestId}/>}<div className="passenger-problem-actions">{problemKind!=="missing"&&<button className="button" onClick={()=>void loadContext()}>Try again</button>}<button className="button button-secondary" onClick={()=>router.replace("/")}>Close feedback</button></div></section></div></main>;
  return <main className="passenger-page"><div className="passenger-shell"><header className="passenger-head"><Brand compact/><span className="secure-note">Passenger-safe feedback</span></header><div className="progress-wrap" aria-label={`Step ${currentStep} of ${totalSteps}`}><div className="progress-label"><span>Step {currentStep} of {totalSteps}</span><span>{stage==="details"?"Your details":stage==="questions"?"Journey questions":"Review"}</span></div><div className="progress"><span style={{width:`${progress}%`}}/></div></div>
    {stage==="details"&&context&&<><p className="eyebrow">Welcome to {context.completion.agencyName}</p><h1 className="passenger-title">Your journey matters to us.</h1><p className="passenger-copy">Review this trip, then tell us a little about yourself before the questionnaire begins.</p>{error&&<ErrorAlert message={error.message} requestId={error.requestId}/>}<section className="card trip-summary"><div className="route"><div className="route-line"><i className="route-dot"/><i className="route-dot"/></div><div className="route-points"><span><small>Pickup</small>{context.trip.pickupLocation}</span><span><small>Destination</small>{context.trip.destination}</span></div></div><div className="trip-summary-grid"><span><small>Journey</small>{context.trip.bookingReference}</span><span><small>Scheduled</small>{formatTripRange(context.trip.scheduledAt,context.trip.scheduledEndAt,context.completion.timezone)}</span><span><small>Vehicle</small>{context.trip.vehicle.displayName}</span><span><small>Driver</small>{context.trip.driver.displayName}</span></div></section><section className="card passenger-card"><h2 className="section-title">About you</h2>{([['name','Name','text'],['phone','Phone number','tel'],['email','Email address','email'],['bookingReference','Booking reference','text']] as const).map(([key,label,type])=><div className="field" key={key}><label htmlFor={key}>{label}</label><input className="input" id={key} type={type} value={String(details[key])} onChange={e=>setDetails({...details,[key]:e.target.value})} aria-invalid={!!fieldErrors[key]} aria-describedby={fieldErrors[key]?`${key}-error`:undefined}/>{fieldErrors[key]&&<small id={`${key}-error`} style={{color:"var(--danger)"}}>{fieldErrors[key]}</small>}</div>)}<h2 className="section-title">Privacy and consent</h2><div className="consent-box">{context.consent.content}</div><label className="check-row"><input type="checkbox" checked={details.consent} onChange={e=>setDetails({...details,consent:e.target.checked})}/><span>I have read the notice and consent to the collection and use of my feedback information.</span></label>{fieldErrors.consent&&<div className="alert">{fieldErrors.consent}</div>}</section><div className="passenger-actions"><span/><button className="button" disabled={startingQuestions} onClick={()=>void nextFromDetails()}>{startingQuestions?"Opening questions…":"Continue to questions →"}</button></div></>}
    {stage==="questions"&&questions[questionIndex]&&<><p className="eyebrow">{questions[questionIndex].category.replaceAll("_"," ")}</p><section className="card passenger-card"><QuestionControl question={questions[questionIndex]} value={answers[questions[questionIndex].id]} onChange={value=>setAnswers({...answers,[questions[questionIndex].id]:value})} error={fieldErrors[questions[questionIndex].id]}/></section><div className="passenger-actions"><button className="button button-secondary" onClick={previousQuestion}>← Previous</button><button className="button" onClick={nextQuestion}>{questionIndex===questions.length-1?"Review feedback →":"Next question →"}</button></div></>}
    {stage==="review"&&context&&<><p className="eyebrow">Almost there</p><h1 className="passenger-title">Review your feedback.</h1><p className="passenger-copy">Submitted feedback cannot be edited. You can go back now if anything needs changing.</p>{error&&<ErrorAlert message={error.message} requestId={error.requestId}/>}<section className="card passenger-card"><div className="review-list">{questions.map(q=><div className="review-row" key={q.id}><small>{q.prompt}</small><strong>{answerLabel(q,answers[q.id])}</strong></div>)}</div></section><div className="passenger-actions"><button className="button button-secondary" onClick={()=>{setQuestionIndex(Math.max(0,questions.length-1));setStage("questions")}}>← Edit answers</button><button className="button" onClick={submit}>Submit feedback</button></div></>}
    {stage==="submitting"&&<section className="completion"><div className="completion-mark" aria-hidden="true">↗</div><h1>Saving your feedback…</h1><p>Please keep this screen open for a moment.</p></section>}
  </div></main>
}
