"use client";
import { FormEvent,useEffect,useState } from "react";
import Link from "next/link";
import type { DataResponse,QuestionnaireSummary,QuestionnaireVersionSummary } from "@/lib/contracts";
import { ApiError,apiRequest,errorMessage } from "@/lib/api";
import { EmptyState,ErrorAlert,LoadingCards,StatusBadge } from "./ui";

export function Questionnaires(){const [items,setItems]=useState<QuestionnaireSummary[]|null>(null);const [versions,setVersions]=useState<Record<string,QuestionnaireVersionSummary[]>>({});const [error,setError]=useState<{message:string;requestId?:string}|null>(null);const [show,setShow]=useState(false);const [busy,setBusy]=useState(false);
  async function load(){setError(null);try{const r=await apiRequest<DataResponse<QuestionnaireSummary[]>>("/api/v1/admin/questionnaires");setItems(r.data)}catch(cause){setItems([]);setError({message:errorMessage(cause),requestId:cause instanceof ApiError?cause.requestId:undefined})}}useEffect(()=>{queueMicrotask(()=>void load())},[]);
  async function loadVersions(id:string){try{const r=await apiRequest<DataResponse<QuestionnaireVersionSummary[]>>(`/api/v1/admin/questionnaires/${id}/versions`);setVersions(v=>({...v,[id]:r.data}))}catch(cause){setError({message:errorMessage(cause),requestId:cause instanceof ApiError?cause.requestId:undefined})}}
  async function create(e:FormEvent<HTMLFormElement>){e.preventDefault();setBusy(true);const d=new FormData(e.currentTarget);try{await apiRequest("/api/v1/admin/questionnaires",{method:"POST",body:JSON.stringify({name:d.get("name")})});setShow(false);await load()}catch(cause){setError({message:errorMessage(cause),requestId:cause instanceof ApiError?cause.requestId:undefined})}finally{setBusy(false)}}
  async function clone(id:string){setBusy(true);try{await apiRequest(`/api/v1/admin/questionnaires/${id}/versions`,{method:"POST"});await loadVersions(id)}catch(cause){setError({message:errorMessage(cause),requestId:cause instanceof ApiError?cause.requestId:undefined})}finally{setBusy(false)}}
  return <><div className="page-header"><div><p className="eyebrow">Versioned passenger form</p><h1>Questionnaires</h1><p>Drafts are editable. Published versions are immutable and remain attached to historical feedback.</p></div><button className="button" onClick={()=>setShow(true)}>New questionnaire</button></div>{error&&<ErrorAlert message={error.message} requestId={error.requestId}/>} {items===null&&<LoadingCards/>}{items?.length===0&&!error&&<EmptyState title="No questionnaires yet">Create a questionnaire and its first draft, then add active questions before publishing.</EmptyState>}{items&&<div className="stack">{items.map(item=><section className="card card-pad" key={item.id}><div className="trip-card-head"><div><span className="eyebrow">Questionnaire</span><h2 className="section-title">{item.name}</h2></div><StatusBadge label={item.status} tone={item.status==="ACTIVE"?"success":"danger"}/></div><div className="trip-actions"><button className="button button-secondary" onClick={()=>loadVersions(item.id)}>Show versions</button><button className="button button-secondary" onClick={()=>clone(item.id)} disabled={busy}>Create next draft</button></div>{versions[item.id]&&<div className="data-list" style={{marginTop:"1rem"}}>{versions[item.id].map(version=><div className="data-row" key={version.id}><span><strong>Version {version.versionNumber}</strong><small>{version.status==="DRAFT"?"Editable until published":"Immutable history"}</small></span><StatusBadge label={version.status} tone={version.status==="ACTIVE"?"success":version.status==="DRAFT"?"warning":"neutral"}/><span>{version.publishedAt?new Intl.DateTimeFormat("en-IN",{dateStyle:"medium"}).format(new Date(version.publishedAt)):"Not published"}</span><Link className="button button-secondary" href={`/admin/questionnaires/${item.id}?version=${version.id}`}>{version.status==="DRAFT"?"Edit draft":"View version"}</Link></div>)}</div>}</section>)}</div>}
  {show&&<div className="dialog-backdrop"><form className="dialog" onSubmit={create}><span className="eyebrow">First draft included</span><h2>Create questionnaire</h2><div className="field"><label htmlFor="name">Name</label><input className="input" id="name" name="name" maxLength={200} required/></div><div className="dialog-actions"><button type="button" className="button button-secondary" onClick={()=>setShow(false)}>Cancel</button><button className="button" disabled={busy}>Create</button></div></form></div>}
  </>;
}
