import type { SubmitFeedbackRequest, SubmissionReceipt } from "./contracts";
import { ApiError, apiRequest, isRetryable } from "./api";
import { backoffDelay } from "./retry-policy";

export type QueueState = "WAITING" | "SYNCING" | "NEEDS_ATTENTION";
export interface QueuedFeedback { id:string; token:string; envelope:SubmitFeedbackRequest; createdAt:string; attempts:number; state:QueueState; nextAttemptAt:string; lastErrorCode?:string }
export interface QueueSummary { count:number; oldestAt:string|null; needsAttention:number }
const DB="eastern-risen-feedback"; const STORE="pending-submissions";
function openDb():Promise<IDBDatabase>{return new Promise((resolve,reject)=>{const request=indexedDB.open(DB,1);request.onupgradeneeded=()=>{if(!request.result.objectStoreNames.contains(STORE))request.result.createObjectStore(STORE,{keyPath:"id"})};request.onsuccess=()=>resolve(request.result);request.onerror=()=>reject(request.error)})}
async function transaction<T>(mode:IDBTransactionMode,work:(store:IDBObjectStore,resolve:(value:T)=>void,reject:(reason?:unknown)=>void)=>void):Promise<T>{const db=await openDb();return new Promise<T>((resolve,reject)=>{const tx=db.transaction(STORE,mode);work(tx.objectStore(STORE),resolve,reject);tx.oncomplete=()=>db.close();tx.onerror=()=>reject(tx.error)})}
export async function enqueue(token:string,envelope:SubmitFeedbackRequest){const item:QueuedFeedback={id:envelope.clientSubmissionId,token,envelope:{...envelope,submissionMode:"OFFLINE_SYNC"},createdAt:new Date().toISOString(),attempts:0,state:"WAITING",nextAttemptAt:new Date().toISOString()};return transaction<void>("readwrite",(store,resolve,reject)=>{const req=store.put(item);req.onsuccess=()=>resolve();req.onerror=()=>reject(req.error)})}
export async function listQueued(){return transaction<QueuedFeedback[]>("readonly",(store,resolve,reject)=>{const req=store.getAll();req.onsuccess=()=>resolve(req.result as QueuedFeedback[]);req.onerror=()=>reject(req.error)})}
async function put(item:QueuedFeedback){return transaction<void>("readwrite",(store,resolve,reject)=>{const req=store.put(item);req.onsuccess=()=>resolve();req.onerror=()=>reject(req.error)})}
async function remove(id:string){return transaction<void>("readwrite",(store,resolve,reject)=>{const req=store.delete(id);req.onsuccess=()=>resolve();req.onerror=()=>reject(req.error)})}
export async function queueSummary():Promise<QueueSummary>{const items=await listQueued();return{count:items.length,oldestAt:items.sort((a,b)=>a.createdAt.localeCompare(b.createdAt))[0]?.createdAt??null,needsAttention:items.filter(i=>i.state==="NEEDS_ATTENTION").length}}
export async function syncQueue(){if(!navigator.onLine)return queueSummary();const items=await listQueued();for(const item of items){if(new Date(item.nextAttemptAt)>new Date())continue;const syncing={...item,state:"SYNCING" as const};await put(syncing);try{await apiRequest<{data:SubmissionReceipt}>("/api/v1/passenger/feedback/submissions",{method:"POST",passengerToken:item.token,body:JSON.stringify(item.envelope),timeoutMs:15000});await remove(item.id)}catch(error){const attempts=item.attempts+1;const retry=isRetryable(error)&&attempts<8;await put({...item,attempts,state:retry?"WAITING":"NEEDS_ATTENTION",nextAttemptAt:new Date(Date.now()+backoffDelay(attempts)).toISOString(),lastErrorCode:error instanceof ApiError?error.code:"UNKNOWN"})}}return queueSummary()}
